"""Regenerate the checked-in 300 typed entities/maps/context test fixture."""
from pathlib import Path

root = Path(__file__).resolve().parent
count = 300
group_size = 20
groups = range(count // group_size)
notice = '// Generated by generate_models.py; edit the generator to regenerate this fixture.\n'

def write(name, content):
    (root / name).write_text(notice + content)

models = '#pragma once\n#include <QString>\n\nnamespace SchemaScale {\n'
for i in range(count):
    models += f'''struct Scale{i:03} {{
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
}};

'''
write('Models.h', models + '} // namespace SchemaScale\n')
maps = '#pragma once\n#include <Q1ORM.h>\n#include "Models.h"\n\nnamespace SchemaScale {\n'
for i in range(count):
    maps += f'''class Scale{i:03}Map {{
public:
    static void ConfigureEntity(Q1Entity<Scale{i:03}>& entity);
}};

'''
write('Maps.h', maps + '} // namespace SchemaScale\n')
header = '''#pragma once
#include <Q1ORM.h>
#include "Models.h"

namespace SchemaScale {
class ApplicationDbContext : public Q1Context {
public:
    explicit ApplicationDbContext(Q1Connection* options, bool evolved = false);
    ~ApplicationDbContext() override;
    bool InsertRows();

'''
for i in range(count):
    header += f'    Q1Entity<Scale{i:03}> scale{i:03};\n'
header += '''
protected:
    void OnModelCreating(Q1ModelBuilder& builder) override;
private:
    bool evolved;
'''
for g in groups:
    header += f'    bool InsertGroup{g:02}();\n    void AddRevisionGroup{g:02}();\n'
write('ApplicationDbContext.h', header + '};\n} // namespace SchemaScale\n')
context = '''#include "ApplicationDbContext.h"
#include "Maps.h"

namespace SchemaScale {
ApplicationDbContext::ApplicationDbContext(Q1Connection* options, bool evolved)
    : evolved(evolved) {
    SetConnection(options, false);
'''
for i in range(count):
    context += f'    RegisterEntity(&scale{i:03});\n'
context += '''}

ApplicationDbContext::~ApplicationDbContext() = default;

void ApplicationDbContext::OnModelCreating(Q1ModelBuilder& builder) {
'''
for i in range(count):
    context += f'    builder.ApplyMap<Scale{i:03}Map>();\n'
context += '    if (evolved) {\n'
for g in groups:
    context += f'        AddRevisionGroup{g:02}();\n'
context += '    }\n}\n\nbool ApplicationDbContext::InsertRows() {\n'
for g in groups:
    context += f'    if (!InsertGroup{g:02}()) return false;\n'
write('ApplicationDbContext.cpp', context + '    return true;\n}\n} // namespace SchemaScale\n')
for g in groups:
    source = '''#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
'''
    for i in range(g * group_size, (g + 1) * group_size):
        source += f'''void Scale{i:03}Map::ConfigureEntity(Q1Entity<Scale{i:03}>& entity) {{
    entity.ToTableName("scale_{i:03}");
    entity.HasKey<&Scale{i:03}::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale{i:03}::name>().IsRequired();
    entity.Property<&Scale{i:03}::parent_id>();
'''
        if i > 0:
            source += f'''    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale{i:03}::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
'''
        source += '    entity.GetTablePtr()->AddIndex({"name"});\n}\n\n'
    source += f'bool ApplicationDbContext::InsertGroup{g:02}() {{\n'
    for i in range(g * group_size, (g + 1) * group_size):
        source += f'    if (!InsertTableRows(scale{i:03}, {i})) return false;\n'
    source += f'    return true;\n}}\n\nvoid ApplicationDbContext::AddRevisionGroup{g:02}() {{\n'
    for i in range(g * group_size, (g + 1) * group_size):
        source += f'''    scale{i:03}.Property<&Scale{i:03}::revision>().IsRequired();
    scale{i:03}.GetTablePtr()->FindColumn("revision")->default_value = "7";
'''
    write(f'Maps{g:02}.cpp', source + '}\n} // namespace SchemaScale\n')
