// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale060Map::ConfigureEntity(Q1Entity<Scale060>& entity) {
    entity.ToTableName("scale_060");
    entity.HasKey<&Scale060::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale060::name>().IsRequired();
    entity.Property<&Scale060::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale060::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale061Map::ConfigureEntity(Q1Entity<Scale061>& entity) {
    entity.ToTableName("scale_061");
    entity.HasKey<&Scale061::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale061::name>().IsRequired();
    entity.Property<&Scale061::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale061::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale062Map::ConfigureEntity(Q1Entity<Scale062>& entity) {
    entity.ToTableName("scale_062");
    entity.HasKey<&Scale062::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale062::name>().IsRequired();
    entity.Property<&Scale062::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale062::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale063Map::ConfigureEntity(Q1Entity<Scale063>& entity) {
    entity.ToTableName("scale_063");
    entity.HasKey<&Scale063::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale063::name>().IsRequired();
    entity.Property<&Scale063::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale063::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale064Map::ConfigureEntity(Q1Entity<Scale064>& entity) {
    entity.ToTableName("scale_064");
    entity.HasKey<&Scale064::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale064::name>().IsRequired();
    entity.Property<&Scale064::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale064::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale065Map::ConfigureEntity(Q1Entity<Scale065>& entity) {
    entity.ToTableName("scale_065");
    entity.HasKey<&Scale065::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale065::name>().IsRequired();
    entity.Property<&Scale065::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale065::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale066Map::ConfigureEntity(Q1Entity<Scale066>& entity) {
    entity.ToTableName("scale_066");
    entity.HasKey<&Scale066::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale066::name>().IsRequired();
    entity.Property<&Scale066::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale066::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale067Map::ConfigureEntity(Q1Entity<Scale067>& entity) {
    entity.ToTableName("scale_067");
    entity.HasKey<&Scale067::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale067::name>().IsRequired();
    entity.Property<&Scale067::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale067::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale068Map::ConfigureEntity(Q1Entity<Scale068>& entity) {
    entity.ToTableName("scale_068");
    entity.HasKey<&Scale068::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale068::name>().IsRequired();
    entity.Property<&Scale068::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale068::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale069Map::ConfigureEntity(Q1Entity<Scale069>& entity) {
    entity.ToTableName("scale_069");
    entity.HasKey<&Scale069::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale069::name>().IsRequired();
    entity.Property<&Scale069::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale069::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale070Map::ConfigureEntity(Q1Entity<Scale070>& entity) {
    entity.ToTableName("scale_070");
    entity.HasKey<&Scale070::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale070::name>().IsRequired();
    entity.Property<&Scale070::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale070::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale071Map::ConfigureEntity(Q1Entity<Scale071>& entity) {
    entity.ToTableName("scale_071");
    entity.HasKey<&Scale071::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale071::name>().IsRequired();
    entity.Property<&Scale071::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale071::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale072Map::ConfigureEntity(Q1Entity<Scale072>& entity) {
    entity.ToTableName("scale_072");
    entity.HasKey<&Scale072::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale072::name>().IsRequired();
    entity.Property<&Scale072::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale072::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale073Map::ConfigureEntity(Q1Entity<Scale073>& entity) {
    entity.ToTableName("scale_073");
    entity.HasKey<&Scale073::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale073::name>().IsRequired();
    entity.Property<&Scale073::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale073::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale074Map::ConfigureEntity(Q1Entity<Scale074>& entity) {
    entity.ToTableName("scale_074");
    entity.HasKey<&Scale074::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale074::name>().IsRequired();
    entity.Property<&Scale074::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale074::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale075Map::ConfigureEntity(Q1Entity<Scale075>& entity) {
    entity.ToTableName("scale_075");
    entity.HasKey<&Scale075::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale075::name>().IsRequired();
    entity.Property<&Scale075::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale075::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale076Map::ConfigureEntity(Q1Entity<Scale076>& entity) {
    entity.ToTableName("scale_076");
    entity.HasKey<&Scale076::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale076::name>().IsRequired();
    entity.Property<&Scale076::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale076::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale077Map::ConfigureEntity(Q1Entity<Scale077>& entity) {
    entity.ToTableName("scale_077");
    entity.HasKey<&Scale077::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale077::name>().IsRequired();
    entity.Property<&Scale077::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale077::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale078Map::ConfigureEntity(Q1Entity<Scale078>& entity) {
    entity.ToTableName("scale_078");
    entity.HasKey<&Scale078::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale078::name>().IsRequired();
    entity.Property<&Scale078::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale078::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale079Map::ConfigureEntity(Q1Entity<Scale079>& entity) {
    entity.ToTableName("scale_079");
    entity.HasKey<&Scale079::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale079::name>().IsRequired();
    entity.Property<&Scale079::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale079::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup03() {
    if (!InsertTableRows(scale060, 60)) return false;
    if (!InsertTableRows(scale061, 61)) return false;
    if (!InsertTableRows(scale062, 62)) return false;
    if (!InsertTableRows(scale063, 63)) return false;
    if (!InsertTableRows(scale064, 64)) return false;
    if (!InsertTableRows(scale065, 65)) return false;
    if (!InsertTableRows(scale066, 66)) return false;
    if (!InsertTableRows(scale067, 67)) return false;
    if (!InsertTableRows(scale068, 68)) return false;
    if (!InsertTableRows(scale069, 69)) return false;
    if (!InsertTableRows(scale070, 70)) return false;
    if (!InsertTableRows(scale071, 71)) return false;
    if (!InsertTableRows(scale072, 72)) return false;
    if (!InsertTableRows(scale073, 73)) return false;
    if (!InsertTableRows(scale074, 74)) return false;
    if (!InsertTableRows(scale075, 75)) return false;
    if (!InsertTableRows(scale076, 76)) return false;
    if (!InsertTableRows(scale077, 77)) return false;
    if (!InsertTableRows(scale078, 78)) return false;
    if (!InsertTableRows(scale079, 79)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup03() {
    scale060.Property<&Scale060::revision>().IsRequired();
    scale060.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale061.Property<&Scale061::revision>().IsRequired();
    scale061.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale062.Property<&Scale062::revision>().IsRequired();
    scale062.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale063.Property<&Scale063::revision>().IsRequired();
    scale063.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale064.Property<&Scale064::revision>().IsRequired();
    scale064.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale065.Property<&Scale065::revision>().IsRequired();
    scale065.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale066.Property<&Scale066::revision>().IsRequired();
    scale066.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale067.Property<&Scale067::revision>().IsRequired();
    scale067.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale068.Property<&Scale068::revision>().IsRequired();
    scale068.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale069.Property<&Scale069::revision>().IsRequired();
    scale069.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale070.Property<&Scale070::revision>().IsRequired();
    scale070.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale071.Property<&Scale071::revision>().IsRequired();
    scale071.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale072.Property<&Scale072::revision>().IsRequired();
    scale072.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale073.Property<&Scale073::revision>().IsRequired();
    scale073.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale074.Property<&Scale074::revision>().IsRequired();
    scale074.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale075.Property<&Scale075::revision>().IsRequired();
    scale075.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale076.Property<&Scale076::revision>().IsRequired();
    scale076.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale077.Property<&Scale077::revision>().IsRequired();
    scale077.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale078.Property<&Scale078::revision>().IsRequired();
    scale078.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale079.Property<&Scale079::revision>().IsRequired();
    scale079.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
