// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale220Map::ConfigureEntity(Q1Entity<Scale220>& entity) {
    entity.ToTableName("scale_220");
    entity.HasKey<&Scale220::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale220::name>().IsRequired();
    entity.Property<&Scale220::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale220::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale221Map::ConfigureEntity(Q1Entity<Scale221>& entity) {
    entity.ToTableName("scale_221");
    entity.HasKey<&Scale221::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale221::name>().IsRequired();
    entity.Property<&Scale221::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale221::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale222Map::ConfigureEntity(Q1Entity<Scale222>& entity) {
    entity.ToTableName("scale_222");
    entity.HasKey<&Scale222::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale222::name>().IsRequired();
    entity.Property<&Scale222::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale222::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale223Map::ConfigureEntity(Q1Entity<Scale223>& entity) {
    entity.ToTableName("scale_223");
    entity.HasKey<&Scale223::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale223::name>().IsRequired();
    entity.Property<&Scale223::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale223::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale224Map::ConfigureEntity(Q1Entity<Scale224>& entity) {
    entity.ToTableName("scale_224");
    entity.HasKey<&Scale224::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale224::name>().IsRequired();
    entity.Property<&Scale224::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale224::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale225Map::ConfigureEntity(Q1Entity<Scale225>& entity) {
    entity.ToTableName("scale_225");
    entity.HasKey<&Scale225::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale225::name>().IsRequired();
    entity.Property<&Scale225::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale225::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale226Map::ConfigureEntity(Q1Entity<Scale226>& entity) {
    entity.ToTableName("scale_226");
    entity.HasKey<&Scale226::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale226::name>().IsRequired();
    entity.Property<&Scale226::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale226::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale227Map::ConfigureEntity(Q1Entity<Scale227>& entity) {
    entity.ToTableName("scale_227");
    entity.HasKey<&Scale227::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale227::name>().IsRequired();
    entity.Property<&Scale227::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale227::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale228Map::ConfigureEntity(Q1Entity<Scale228>& entity) {
    entity.ToTableName("scale_228");
    entity.HasKey<&Scale228::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale228::name>().IsRequired();
    entity.Property<&Scale228::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale228::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale229Map::ConfigureEntity(Q1Entity<Scale229>& entity) {
    entity.ToTableName("scale_229");
    entity.HasKey<&Scale229::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale229::name>().IsRequired();
    entity.Property<&Scale229::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale229::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale230Map::ConfigureEntity(Q1Entity<Scale230>& entity) {
    entity.ToTableName("scale_230");
    entity.HasKey<&Scale230::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale230::name>().IsRequired();
    entity.Property<&Scale230::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale230::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale231Map::ConfigureEntity(Q1Entity<Scale231>& entity) {
    entity.ToTableName("scale_231");
    entity.HasKey<&Scale231::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale231::name>().IsRequired();
    entity.Property<&Scale231::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale231::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale232Map::ConfigureEntity(Q1Entity<Scale232>& entity) {
    entity.ToTableName("scale_232");
    entity.HasKey<&Scale232::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale232::name>().IsRequired();
    entity.Property<&Scale232::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale232::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale233Map::ConfigureEntity(Q1Entity<Scale233>& entity) {
    entity.ToTableName("scale_233");
    entity.HasKey<&Scale233::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale233::name>().IsRequired();
    entity.Property<&Scale233::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale233::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale234Map::ConfigureEntity(Q1Entity<Scale234>& entity) {
    entity.ToTableName("scale_234");
    entity.HasKey<&Scale234::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale234::name>().IsRequired();
    entity.Property<&Scale234::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale234::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale235Map::ConfigureEntity(Q1Entity<Scale235>& entity) {
    entity.ToTableName("scale_235");
    entity.HasKey<&Scale235::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale235::name>().IsRequired();
    entity.Property<&Scale235::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale235::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale236Map::ConfigureEntity(Q1Entity<Scale236>& entity) {
    entity.ToTableName("scale_236");
    entity.HasKey<&Scale236::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale236::name>().IsRequired();
    entity.Property<&Scale236::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale236::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale237Map::ConfigureEntity(Q1Entity<Scale237>& entity) {
    entity.ToTableName("scale_237");
    entity.HasKey<&Scale237::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale237::name>().IsRequired();
    entity.Property<&Scale237::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale237::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale238Map::ConfigureEntity(Q1Entity<Scale238>& entity) {
    entity.ToTableName("scale_238");
    entity.HasKey<&Scale238::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale238::name>().IsRequired();
    entity.Property<&Scale238::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale238::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale239Map::ConfigureEntity(Q1Entity<Scale239>& entity) {
    entity.ToTableName("scale_239");
    entity.HasKey<&Scale239::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale239::name>().IsRequired();
    entity.Property<&Scale239::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale239::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup11() {
    if (!InsertTableRows(scale220, 220)) return false;
    if (!InsertTableRows(scale221, 221)) return false;
    if (!InsertTableRows(scale222, 222)) return false;
    if (!InsertTableRows(scale223, 223)) return false;
    if (!InsertTableRows(scale224, 224)) return false;
    if (!InsertTableRows(scale225, 225)) return false;
    if (!InsertTableRows(scale226, 226)) return false;
    if (!InsertTableRows(scale227, 227)) return false;
    if (!InsertTableRows(scale228, 228)) return false;
    if (!InsertTableRows(scale229, 229)) return false;
    if (!InsertTableRows(scale230, 230)) return false;
    if (!InsertTableRows(scale231, 231)) return false;
    if (!InsertTableRows(scale232, 232)) return false;
    if (!InsertTableRows(scale233, 233)) return false;
    if (!InsertTableRows(scale234, 234)) return false;
    if (!InsertTableRows(scale235, 235)) return false;
    if (!InsertTableRows(scale236, 236)) return false;
    if (!InsertTableRows(scale237, 237)) return false;
    if (!InsertTableRows(scale238, 238)) return false;
    if (!InsertTableRows(scale239, 239)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup11() {
    scale220.Property<&Scale220::revision>().IsRequired();
    scale220.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale221.Property<&Scale221::revision>().IsRequired();
    scale221.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale222.Property<&Scale222::revision>().IsRequired();
    scale222.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale223.Property<&Scale223::revision>().IsRequired();
    scale223.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale224.Property<&Scale224::revision>().IsRequired();
    scale224.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale225.Property<&Scale225::revision>().IsRequired();
    scale225.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale226.Property<&Scale226::revision>().IsRequired();
    scale226.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale227.Property<&Scale227::revision>().IsRequired();
    scale227.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale228.Property<&Scale228::revision>().IsRequired();
    scale228.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale229.Property<&Scale229::revision>().IsRequired();
    scale229.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale230.Property<&Scale230::revision>().IsRequired();
    scale230.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale231.Property<&Scale231::revision>().IsRequired();
    scale231.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale232.Property<&Scale232::revision>().IsRequired();
    scale232.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale233.Property<&Scale233::revision>().IsRequired();
    scale233.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale234.Property<&Scale234::revision>().IsRequired();
    scale234.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale235.Property<&Scale235::revision>().IsRequired();
    scale235.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale236.Property<&Scale236::revision>().IsRequired();
    scale236.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale237.Property<&Scale237::revision>().IsRequired();
    scale237.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale238.Property<&Scale238::revision>().IsRequired();
    scale238.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale239.Property<&Scale239::revision>().IsRequired();
    scale239.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
