// Generated by generate_models.py; edit the generator to regenerate this fixture.
#pragma once
#include <Q1ORM.h>
#include "Models.h"

namespace SchemaScale {
class Scale000Map {
public:
    static void ConfigureEntity(Q1Entity<Scale000>& entity);
};

class Scale001Map {
public:
    static void ConfigureEntity(Q1Entity<Scale001>& entity);
};

class Scale002Map {
public:
    static void ConfigureEntity(Q1Entity<Scale002>& entity);
};

class Scale003Map {
public:
    static void ConfigureEntity(Q1Entity<Scale003>& entity);
};

class Scale004Map {
public:
    static void ConfigureEntity(Q1Entity<Scale004>& entity);
};

class Scale005Map {
public:
    static void ConfigureEntity(Q1Entity<Scale005>& entity);
};

class Scale006Map {
public:
    static void ConfigureEntity(Q1Entity<Scale006>& entity);
};

class Scale007Map {
public:
    static void ConfigureEntity(Q1Entity<Scale007>& entity);
};

class Scale008Map {
public:
    static void ConfigureEntity(Q1Entity<Scale008>& entity);
};

class Scale009Map {
public:
    static void ConfigureEntity(Q1Entity<Scale009>& entity);
};

class Scale010Map {
public:
    static void ConfigureEntity(Q1Entity<Scale010>& entity);
};

class Scale011Map {
public:
    static void ConfigureEntity(Q1Entity<Scale011>& entity);
};

class Scale012Map {
public:
    static void ConfigureEntity(Q1Entity<Scale012>& entity);
};

class Scale013Map {
public:
    static void ConfigureEntity(Q1Entity<Scale013>& entity);
};

class Scale014Map {
public:
    static void ConfigureEntity(Q1Entity<Scale014>& entity);
};

class Scale015Map {
public:
    static void ConfigureEntity(Q1Entity<Scale015>& entity);
};

class Scale016Map {
public:
    static void ConfigureEntity(Q1Entity<Scale016>& entity);
};

class Scale017Map {
public:
    static void ConfigureEntity(Q1Entity<Scale017>& entity);
};

class Scale018Map {
public:
    static void ConfigureEntity(Q1Entity<Scale018>& entity);
};

class Scale019Map {
public:
    static void ConfigureEntity(Q1Entity<Scale019>& entity);
};

class Scale020Map {
public:
    static void ConfigureEntity(Q1Entity<Scale020>& entity);
};

class Scale021Map {
public:
    static void ConfigureEntity(Q1Entity<Scale021>& entity);
};

class Scale022Map {
public:
    static void ConfigureEntity(Q1Entity<Scale022>& entity);
};

class Scale023Map {
public:
    static void ConfigureEntity(Q1Entity<Scale023>& entity);
};

class Scale024Map {
public:
    static void ConfigureEntity(Q1Entity<Scale024>& entity);
};

class Scale025Map {
public:
    static void ConfigureEntity(Q1Entity<Scale025>& entity);
};

class Scale026Map {
public:
    static void ConfigureEntity(Q1Entity<Scale026>& entity);
};

class Scale027Map {
public:
    static void ConfigureEntity(Q1Entity<Scale027>& entity);
};

class Scale028Map {
public:
    static void ConfigureEntity(Q1Entity<Scale028>& entity);
};

class Scale029Map {
public:
    static void ConfigureEntity(Q1Entity<Scale029>& entity);
};

class Scale030Map {
public:
    static void ConfigureEntity(Q1Entity<Scale030>& entity);
};

class Scale031Map {
public:
    static void ConfigureEntity(Q1Entity<Scale031>& entity);
};

class Scale032Map {
public:
    static void ConfigureEntity(Q1Entity<Scale032>& entity);
};

class Scale033Map {
public:
    static void ConfigureEntity(Q1Entity<Scale033>& entity);
};

class Scale034Map {
public:
    static void ConfigureEntity(Q1Entity<Scale034>& entity);
};

class Scale035Map {
public:
    static void ConfigureEntity(Q1Entity<Scale035>& entity);
};

class Scale036Map {
public:
    static void ConfigureEntity(Q1Entity<Scale036>& entity);
};

class Scale037Map {
public:
    static void ConfigureEntity(Q1Entity<Scale037>& entity);
};

class Scale038Map {
public:
    static void ConfigureEntity(Q1Entity<Scale038>& entity);
};

class Scale039Map {
public:
    static void ConfigureEntity(Q1Entity<Scale039>& entity);
};

class Scale040Map {
public:
    static void ConfigureEntity(Q1Entity<Scale040>& entity);
};

class Scale041Map {
public:
    static void ConfigureEntity(Q1Entity<Scale041>& entity);
};

class Scale042Map {
public:
    static void ConfigureEntity(Q1Entity<Scale042>& entity);
};

class Scale043Map {
public:
    static void ConfigureEntity(Q1Entity<Scale043>& entity);
};

class Scale044Map {
public:
    static void ConfigureEntity(Q1Entity<Scale044>& entity);
};

class Scale045Map {
public:
    static void ConfigureEntity(Q1Entity<Scale045>& entity);
};

class Scale046Map {
public:
    static void ConfigureEntity(Q1Entity<Scale046>& entity);
};

class Scale047Map {
public:
    static void ConfigureEntity(Q1Entity<Scale047>& entity);
};

class Scale048Map {
public:
    static void ConfigureEntity(Q1Entity<Scale048>& entity);
};

class Scale049Map {
public:
    static void ConfigureEntity(Q1Entity<Scale049>& entity);
};

class Scale050Map {
public:
    static void ConfigureEntity(Q1Entity<Scale050>& entity);
};

class Scale051Map {
public:
    static void ConfigureEntity(Q1Entity<Scale051>& entity);
};

class Scale052Map {
public:
    static void ConfigureEntity(Q1Entity<Scale052>& entity);
};

class Scale053Map {
public:
    static void ConfigureEntity(Q1Entity<Scale053>& entity);
};

class Scale054Map {
public:
    static void ConfigureEntity(Q1Entity<Scale054>& entity);
};

class Scale055Map {
public:
    static void ConfigureEntity(Q1Entity<Scale055>& entity);
};

class Scale056Map {
public:
    static void ConfigureEntity(Q1Entity<Scale056>& entity);
};

class Scale057Map {
public:
    static void ConfigureEntity(Q1Entity<Scale057>& entity);
};

class Scale058Map {
public:
    static void ConfigureEntity(Q1Entity<Scale058>& entity);
};

class Scale059Map {
public:
    static void ConfigureEntity(Q1Entity<Scale059>& entity);
};

class Scale060Map {
public:
    static void ConfigureEntity(Q1Entity<Scale060>& entity);
};

class Scale061Map {
public:
    static void ConfigureEntity(Q1Entity<Scale061>& entity);
};

class Scale062Map {
public:
    static void ConfigureEntity(Q1Entity<Scale062>& entity);
};

class Scale063Map {
public:
    static void ConfigureEntity(Q1Entity<Scale063>& entity);
};

class Scale064Map {
public:
    static void ConfigureEntity(Q1Entity<Scale064>& entity);
};

class Scale065Map {
public:
    static void ConfigureEntity(Q1Entity<Scale065>& entity);
};

class Scale066Map {
public:
    static void ConfigureEntity(Q1Entity<Scale066>& entity);
};

class Scale067Map {
public:
    static void ConfigureEntity(Q1Entity<Scale067>& entity);
};

class Scale068Map {
public:
    static void ConfigureEntity(Q1Entity<Scale068>& entity);
};

class Scale069Map {
public:
    static void ConfigureEntity(Q1Entity<Scale069>& entity);
};

class Scale070Map {
public:
    static void ConfigureEntity(Q1Entity<Scale070>& entity);
};

class Scale071Map {
public:
    static void ConfigureEntity(Q1Entity<Scale071>& entity);
};

class Scale072Map {
public:
    static void ConfigureEntity(Q1Entity<Scale072>& entity);
};

class Scale073Map {
public:
    static void ConfigureEntity(Q1Entity<Scale073>& entity);
};

class Scale074Map {
public:
    static void ConfigureEntity(Q1Entity<Scale074>& entity);
};

class Scale075Map {
public:
    static void ConfigureEntity(Q1Entity<Scale075>& entity);
};

class Scale076Map {
public:
    static void ConfigureEntity(Q1Entity<Scale076>& entity);
};

class Scale077Map {
public:
    static void ConfigureEntity(Q1Entity<Scale077>& entity);
};

class Scale078Map {
public:
    static void ConfigureEntity(Q1Entity<Scale078>& entity);
};

class Scale079Map {
public:
    static void ConfigureEntity(Q1Entity<Scale079>& entity);
};

class Scale080Map {
public:
    static void ConfigureEntity(Q1Entity<Scale080>& entity);
};

class Scale081Map {
public:
    static void ConfigureEntity(Q1Entity<Scale081>& entity);
};

class Scale082Map {
public:
    static void ConfigureEntity(Q1Entity<Scale082>& entity);
};

class Scale083Map {
public:
    static void ConfigureEntity(Q1Entity<Scale083>& entity);
};

class Scale084Map {
public:
    static void ConfigureEntity(Q1Entity<Scale084>& entity);
};

class Scale085Map {
public:
    static void ConfigureEntity(Q1Entity<Scale085>& entity);
};

class Scale086Map {
public:
    static void ConfigureEntity(Q1Entity<Scale086>& entity);
};

class Scale087Map {
public:
    static void ConfigureEntity(Q1Entity<Scale087>& entity);
};

class Scale088Map {
public:
    static void ConfigureEntity(Q1Entity<Scale088>& entity);
};

class Scale089Map {
public:
    static void ConfigureEntity(Q1Entity<Scale089>& entity);
};

class Scale090Map {
public:
    static void ConfigureEntity(Q1Entity<Scale090>& entity);
};

class Scale091Map {
public:
    static void ConfigureEntity(Q1Entity<Scale091>& entity);
};

class Scale092Map {
public:
    static void ConfigureEntity(Q1Entity<Scale092>& entity);
};

class Scale093Map {
public:
    static void ConfigureEntity(Q1Entity<Scale093>& entity);
};

class Scale094Map {
public:
    static void ConfigureEntity(Q1Entity<Scale094>& entity);
};

class Scale095Map {
public:
    static void ConfigureEntity(Q1Entity<Scale095>& entity);
};

class Scale096Map {
public:
    static void ConfigureEntity(Q1Entity<Scale096>& entity);
};

class Scale097Map {
public:
    static void ConfigureEntity(Q1Entity<Scale097>& entity);
};

class Scale098Map {
public:
    static void ConfigureEntity(Q1Entity<Scale098>& entity);
};

class Scale099Map {
public:
    static void ConfigureEntity(Q1Entity<Scale099>& entity);
};

class Scale100Map {
public:
    static void ConfigureEntity(Q1Entity<Scale100>& entity);
};

class Scale101Map {
public:
    static void ConfigureEntity(Q1Entity<Scale101>& entity);
};

class Scale102Map {
public:
    static void ConfigureEntity(Q1Entity<Scale102>& entity);
};

class Scale103Map {
public:
    static void ConfigureEntity(Q1Entity<Scale103>& entity);
};

class Scale104Map {
public:
    static void ConfigureEntity(Q1Entity<Scale104>& entity);
};

class Scale105Map {
public:
    static void ConfigureEntity(Q1Entity<Scale105>& entity);
};

class Scale106Map {
public:
    static void ConfigureEntity(Q1Entity<Scale106>& entity);
};

class Scale107Map {
public:
    static void ConfigureEntity(Q1Entity<Scale107>& entity);
};

class Scale108Map {
public:
    static void ConfigureEntity(Q1Entity<Scale108>& entity);
};

class Scale109Map {
public:
    static void ConfigureEntity(Q1Entity<Scale109>& entity);
};

class Scale110Map {
public:
    static void ConfigureEntity(Q1Entity<Scale110>& entity);
};

class Scale111Map {
public:
    static void ConfigureEntity(Q1Entity<Scale111>& entity);
};

class Scale112Map {
public:
    static void ConfigureEntity(Q1Entity<Scale112>& entity);
};

class Scale113Map {
public:
    static void ConfigureEntity(Q1Entity<Scale113>& entity);
};

class Scale114Map {
public:
    static void ConfigureEntity(Q1Entity<Scale114>& entity);
};

class Scale115Map {
public:
    static void ConfigureEntity(Q1Entity<Scale115>& entity);
};

class Scale116Map {
public:
    static void ConfigureEntity(Q1Entity<Scale116>& entity);
};

class Scale117Map {
public:
    static void ConfigureEntity(Q1Entity<Scale117>& entity);
};

class Scale118Map {
public:
    static void ConfigureEntity(Q1Entity<Scale118>& entity);
};

class Scale119Map {
public:
    static void ConfigureEntity(Q1Entity<Scale119>& entity);
};

class Scale120Map {
public:
    static void ConfigureEntity(Q1Entity<Scale120>& entity);
};

class Scale121Map {
public:
    static void ConfigureEntity(Q1Entity<Scale121>& entity);
};

class Scale122Map {
public:
    static void ConfigureEntity(Q1Entity<Scale122>& entity);
};

class Scale123Map {
public:
    static void ConfigureEntity(Q1Entity<Scale123>& entity);
};

class Scale124Map {
public:
    static void ConfigureEntity(Q1Entity<Scale124>& entity);
};

class Scale125Map {
public:
    static void ConfigureEntity(Q1Entity<Scale125>& entity);
};

class Scale126Map {
public:
    static void ConfigureEntity(Q1Entity<Scale126>& entity);
};

class Scale127Map {
public:
    static void ConfigureEntity(Q1Entity<Scale127>& entity);
};

class Scale128Map {
public:
    static void ConfigureEntity(Q1Entity<Scale128>& entity);
};

class Scale129Map {
public:
    static void ConfigureEntity(Q1Entity<Scale129>& entity);
};

class Scale130Map {
public:
    static void ConfigureEntity(Q1Entity<Scale130>& entity);
};

class Scale131Map {
public:
    static void ConfigureEntity(Q1Entity<Scale131>& entity);
};

class Scale132Map {
public:
    static void ConfigureEntity(Q1Entity<Scale132>& entity);
};

class Scale133Map {
public:
    static void ConfigureEntity(Q1Entity<Scale133>& entity);
};

class Scale134Map {
public:
    static void ConfigureEntity(Q1Entity<Scale134>& entity);
};

class Scale135Map {
public:
    static void ConfigureEntity(Q1Entity<Scale135>& entity);
};

class Scale136Map {
public:
    static void ConfigureEntity(Q1Entity<Scale136>& entity);
};

class Scale137Map {
public:
    static void ConfigureEntity(Q1Entity<Scale137>& entity);
};

class Scale138Map {
public:
    static void ConfigureEntity(Q1Entity<Scale138>& entity);
};

class Scale139Map {
public:
    static void ConfigureEntity(Q1Entity<Scale139>& entity);
};

class Scale140Map {
public:
    static void ConfigureEntity(Q1Entity<Scale140>& entity);
};

class Scale141Map {
public:
    static void ConfigureEntity(Q1Entity<Scale141>& entity);
};

class Scale142Map {
public:
    static void ConfigureEntity(Q1Entity<Scale142>& entity);
};

class Scale143Map {
public:
    static void ConfigureEntity(Q1Entity<Scale143>& entity);
};

class Scale144Map {
public:
    static void ConfigureEntity(Q1Entity<Scale144>& entity);
};

class Scale145Map {
public:
    static void ConfigureEntity(Q1Entity<Scale145>& entity);
};

class Scale146Map {
public:
    static void ConfigureEntity(Q1Entity<Scale146>& entity);
};

class Scale147Map {
public:
    static void ConfigureEntity(Q1Entity<Scale147>& entity);
};

class Scale148Map {
public:
    static void ConfigureEntity(Q1Entity<Scale148>& entity);
};

class Scale149Map {
public:
    static void ConfigureEntity(Q1Entity<Scale149>& entity);
};

class Scale150Map {
public:
    static void ConfigureEntity(Q1Entity<Scale150>& entity);
};

class Scale151Map {
public:
    static void ConfigureEntity(Q1Entity<Scale151>& entity);
};

class Scale152Map {
public:
    static void ConfigureEntity(Q1Entity<Scale152>& entity);
};

class Scale153Map {
public:
    static void ConfigureEntity(Q1Entity<Scale153>& entity);
};

class Scale154Map {
public:
    static void ConfigureEntity(Q1Entity<Scale154>& entity);
};

class Scale155Map {
public:
    static void ConfigureEntity(Q1Entity<Scale155>& entity);
};

class Scale156Map {
public:
    static void ConfigureEntity(Q1Entity<Scale156>& entity);
};

class Scale157Map {
public:
    static void ConfigureEntity(Q1Entity<Scale157>& entity);
};

class Scale158Map {
public:
    static void ConfigureEntity(Q1Entity<Scale158>& entity);
};

class Scale159Map {
public:
    static void ConfigureEntity(Q1Entity<Scale159>& entity);
};

class Scale160Map {
public:
    static void ConfigureEntity(Q1Entity<Scale160>& entity);
};

class Scale161Map {
public:
    static void ConfigureEntity(Q1Entity<Scale161>& entity);
};

class Scale162Map {
public:
    static void ConfigureEntity(Q1Entity<Scale162>& entity);
};

class Scale163Map {
public:
    static void ConfigureEntity(Q1Entity<Scale163>& entity);
};

class Scale164Map {
public:
    static void ConfigureEntity(Q1Entity<Scale164>& entity);
};

class Scale165Map {
public:
    static void ConfigureEntity(Q1Entity<Scale165>& entity);
};

class Scale166Map {
public:
    static void ConfigureEntity(Q1Entity<Scale166>& entity);
};

class Scale167Map {
public:
    static void ConfigureEntity(Q1Entity<Scale167>& entity);
};

class Scale168Map {
public:
    static void ConfigureEntity(Q1Entity<Scale168>& entity);
};

class Scale169Map {
public:
    static void ConfigureEntity(Q1Entity<Scale169>& entity);
};

class Scale170Map {
public:
    static void ConfigureEntity(Q1Entity<Scale170>& entity);
};

class Scale171Map {
public:
    static void ConfigureEntity(Q1Entity<Scale171>& entity);
};

class Scale172Map {
public:
    static void ConfigureEntity(Q1Entity<Scale172>& entity);
};

class Scale173Map {
public:
    static void ConfigureEntity(Q1Entity<Scale173>& entity);
};

class Scale174Map {
public:
    static void ConfigureEntity(Q1Entity<Scale174>& entity);
};

class Scale175Map {
public:
    static void ConfigureEntity(Q1Entity<Scale175>& entity);
};

class Scale176Map {
public:
    static void ConfigureEntity(Q1Entity<Scale176>& entity);
};

class Scale177Map {
public:
    static void ConfigureEntity(Q1Entity<Scale177>& entity);
};

class Scale178Map {
public:
    static void ConfigureEntity(Q1Entity<Scale178>& entity);
};

class Scale179Map {
public:
    static void ConfigureEntity(Q1Entity<Scale179>& entity);
};

class Scale180Map {
public:
    static void ConfigureEntity(Q1Entity<Scale180>& entity);
};

class Scale181Map {
public:
    static void ConfigureEntity(Q1Entity<Scale181>& entity);
};

class Scale182Map {
public:
    static void ConfigureEntity(Q1Entity<Scale182>& entity);
};

class Scale183Map {
public:
    static void ConfigureEntity(Q1Entity<Scale183>& entity);
};

class Scale184Map {
public:
    static void ConfigureEntity(Q1Entity<Scale184>& entity);
};

class Scale185Map {
public:
    static void ConfigureEntity(Q1Entity<Scale185>& entity);
};

class Scale186Map {
public:
    static void ConfigureEntity(Q1Entity<Scale186>& entity);
};

class Scale187Map {
public:
    static void ConfigureEntity(Q1Entity<Scale187>& entity);
};

class Scale188Map {
public:
    static void ConfigureEntity(Q1Entity<Scale188>& entity);
};

class Scale189Map {
public:
    static void ConfigureEntity(Q1Entity<Scale189>& entity);
};

class Scale190Map {
public:
    static void ConfigureEntity(Q1Entity<Scale190>& entity);
};

class Scale191Map {
public:
    static void ConfigureEntity(Q1Entity<Scale191>& entity);
};

class Scale192Map {
public:
    static void ConfigureEntity(Q1Entity<Scale192>& entity);
};

class Scale193Map {
public:
    static void ConfigureEntity(Q1Entity<Scale193>& entity);
};

class Scale194Map {
public:
    static void ConfigureEntity(Q1Entity<Scale194>& entity);
};

class Scale195Map {
public:
    static void ConfigureEntity(Q1Entity<Scale195>& entity);
};

class Scale196Map {
public:
    static void ConfigureEntity(Q1Entity<Scale196>& entity);
};

class Scale197Map {
public:
    static void ConfigureEntity(Q1Entity<Scale197>& entity);
};

class Scale198Map {
public:
    static void ConfigureEntity(Q1Entity<Scale198>& entity);
};

class Scale199Map {
public:
    static void ConfigureEntity(Q1Entity<Scale199>& entity);
};

class Scale200Map {
public:
    static void ConfigureEntity(Q1Entity<Scale200>& entity);
};

class Scale201Map {
public:
    static void ConfigureEntity(Q1Entity<Scale201>& entity);
};

class Scale202Map {
public:
    static void ConfigureEntity(Q1Entity<Scale202>& entity);
};

class Scale203Map {
public:
    static void ConfigureEntity(Q1Entity<Scale203>& entity);
};

class Scale204Map {
public:
    static void ConfigureEntity(Q1Entity<Scale204>& entity);
};

class Scale205Map {
public:
    static void ConfigureEntity(Q1Entity<Scale205>& entity);
};

class Scale206Map {
public:
    static void ConfigureEntity(Q1Entity<Scale206>& entity);
};

class Scale207Map {
public:
    static void ConfigureEntity(Q1Entity<Scale207>& entity);
};

class Scale208Map {
public:
    static void ConfigureEntity(Q1Entity<Scale208>& entity);
};

class Scale209Map {
public:
    static void ConfigureEntity(Q1Entity<Scale209>& entity);
};

class Scale210Map {
public:
    static void ConfigureEntity(Q1Entity<Scale210>& entity);
};

class Scale211Map {
public:
    static void ConfigureEntity(Q1Entity<Scale211>& entity);
};

class Scale212Map {
public:
    static void ConfigureEntity(Q1Entity<Scale212>& entity);
};

class Scale213Map {
public:
    static void ConfigureEntity(Q1Entity<Scale213>& entity);
};

class Scale214Map {
public:
    static void ConfigureEntity(Q1Entity<Scale214>& entity);
};

class Scale215Map {
public:
    static void ConfigureEntity(Q1Entity<Scale215>& entity);
};

class Scale216Map {
public:
    static void ConfigureEntity(Q1Entity<Scale216>& entity);
};

class Scale217Map {
public:
    static void ConfigureEntity(Q1Entity<Scale217>& entity);
};

class Scale218Map {
public:
    static void ConfigureEntity(Q1Entity<Scale218>& entity);
};

class Scale219Map {
public:
    static void ConfigureEntity(Q1Entity<Scale219>& entity);
};

class Scale220Map {
public:
    static void ConfigureEntity(Q1Entity<Scale220>& entity);
};

class Scale221Map {
public:
    static void ConfigureEntity(Q1Entity<Scale221>& entity);
};

class Scale222Map {
public:
    static void ConfigureEntity(Q1Entity<Scale222>& entity);
};

class Scale223Map {
public:
    static void ConfigureEntity(Q1Entity<Scale223>& entity);
};

class Scale224Map {
public:
    static void ConfigureEntity(Q1Entity<Scale224>& entity);
};

class Scale225Map {
public:
    static void ConfigureEntity(Q1Entity<Scale225>& entity);
};

class Scale226Map {
public:
    static void ConfigureEntity(Q1Entity<Scale226>& entity);
};

class Scale227Map {
public:
    static void ConfigureEntity(Q1Entity<Scale227>& entity);
};

class Scale228Map {
public:
    static void ConfigureEntity(Q1Entity<Scale228>& entity);
};

class Scale229Map {
public:
    static void ConfigureEntity(Q1Entity<Scale229>& entity);
};

class Scale230Map {
public:
    static void ConfigureEntity(Q1Entity<Scale230>& entity);
};

class Scale231Map {
public:
    static void ConfigureEntity(Q1Entity<Scale231>& entity);
};

class Scale232Map {
public:
    static void ConfigureEntity(Q1Entity<Scale232>& entity);
};

class Scale233Map {
public:
    static void ConfigureEntity(Q1Entity<Scale233>& entity);
};

class Scale234Map {
public:
    static void ConfigureEntity(Q1Entity<Scale234>& entity);
};

class Scale235Map {
public:
    static void ConfigureEntity(Q1Entity<Scale235>& entity);
};

class Scale236Map {
public:
    static void ConfigureEntity(Q1Entity<Scale236>& entity);
};

class Scale237Map {
public:
    static void ConfigureEntity(Q1Entity<Scale237>& entity);
};

class Scale238Map {
public:
    static void ConfigureEntity(Q1Entity<Scale238>& entity);
};

class Scale239Map {
public:
    static void ConfigureEntity(Q1Entity<Scale239>& entity);
};

class Scale240Map {
public:
    static void ConfigureEntity(Q1Entity<Scale240>& entity);
};

class Scale241Map {
public:
    static void ConfigureEntity(Q1Entity<Scale241>& entity);
};

class Scale242Map {
public:
    static void ConfigureEntity(Q1Entity<Scale242>& entity);
};

class Scale243Map {
public:
    static void ConfigureEntity(Q1Entity<Scale243>& entity);
};

class Scale244Map {
public:
    static void ConfigureEntity(Q1Entity<Scale244>& entity);
};

class Scale245Map {
public:
    static void ConfigureEntity(Q1Entity<Scale245>& entity);
};

class Scale246Map {
public:
    static void ConfigureEntity(Q1Entity<Scale246>& entity);
};

class Scale247Map {
public:
    static void ConfigureEntity(Q1Entity<Scale247>& entity);
};

class Scale248Map {
public:
    static void ConfigureEntity(Q1Entity<Scale248>& entity);
};

class Scale249Map {
public:
    static void ConfigureEntity(Q1Entity<Scale249>& entity);
};

class Scale250Map {
public:
    static void ConfigureEntity(Q1Entity<Scale250>& entity);
};

class Scale251Map {
public:
    static void ConfigureEntity(Q1Entity<Scale251>& entity);
};

class Scale252Map {
public:
    static void ConfigureEntity(Q1Entity<Scale252>& entity);
};

class Scale253Map {
public:
    static void ConfigureEntity(Q1Entity<Scale253>& entity);
};

class Scale254Map {
public:
    static void ConfigureEntity(Q1Entity<Scale254>& entity);
};

class Scale255Map {
public:
    static void ConfigureEntity(Q1Entity<Scale255>& entity);
};

class Scale256Map {
public:
    static void ConfigureEntity(Q1Entity<Scale256>& entity);
};

class Scale257Map {
public:
    static void ConfigureEntity(Q1Entity<Scale257>& entity);
};

class Scale258Map {
public:
    static void ConfigureEntity(Q1Entity<Scale258>& entity);
};

class Scale259Map {
public:
    static void ConfigureEntity(Q1Entity<Scale259>& entity);
};

class Scale260Map {
public:
    static void ConfigureEntity(Q1Entity<Scale260>& entity);
};

class Scale261Map {
public:
    static void ConfigureEntity(Q1Entity<Scale261>& entity);
};

class Scale262Map {
public:
    static void ConfigureEntity(Q1Entity<Scale262>& entity);
};

class Scale263Map {
public:
    static void ConfigureEntity(Q1Entity<Scale263>& entity);
};

class Scale264Map {
public:
    static void ConfigureEntity(Q1Entity<Scale264>& entity);
};

class Scale265Map {
public:
    static void ConfigureEntity(Q1Entity<Scale265>& entity);
};

class Scale266Map {
public:
    static void ConfigureEntity(Q1Entity<Scale266>& entity);
};

class Scale267Map {
public:
    static void ConfigureEntity(Q1Entity<Scale267>& entity);
};

class Scale268Map {
public:
    static void ConfigureEntity(Q1Entity<Scale268>& entity);
};

class Scale269Map {
public:
    static void ConfigureEntity(Q1Entity<Scale269>& entity);
};

class Scale270Map {
public:
    static void ConfigureEntity(Q1Entity<Scale270>& entity);
};

class Scale271Map {
public:
    static void ConfigureEntity(Q1Entity<Scale271>& entity);
};

class Scale272Map {
public:
    static void ConfigureEntity(Q1Entity<Scale272>& entity);
};

class Scale273Map {
public:
    static void ConfigureEntity(Q1Entity<Scale273>& entity);
};

class Scale274Map {
public:
    static void ConfigureEntity(Q1Entity<Scale274>& entity);
};

class Scale275Map {
public:
    static void ConfigureEntity(Q1Entity<Scale275>& entity);
};

class Scale276Map {
public:
    static void ConfigureEntity(Q1Entity<Scale276>& entity);
};

class Scale277Map {
public:
    static void ConfigureEntity(Q1Entity<Scale277>& entity);
};

class Scale278Map {
public:
    static void ConfigureEntity(Q1Entity<Scale278>& entity);
};

class Scale279Map {
public:
    static void ConfigureEntity(Q1Entity<Scale279>& entity);
};

class Scale280Map {
public:
    static void ConfigureEntity(Q1Entity<Scale280>& entity);
};

class Scale281Map {
public:
    static void ConfigureEntity(Q1Entity<Scale281>& entity);
};

class Scale282Map {
public:
    static void ConfigureEntity(Q1Entity<Scale282>& entity);
};

class Scale283Map {
public:
    static void ConfigureEntity(Q1Entity<Scale283>& entity);
};

class Scale284Map {
public:
    static void ConfigureEntity(Q1Entity<Scale284>& entity);
};

class Scale285Map {
public:
    static void ConfigureEntity(Q1Entity<Scale285>& entity);
};

class Scale286Map {
public:
    static void ConfigureEntity(Q1Entity<Scale286>& entity);
};

class Scale287Map {
public:
    static void ConfigureEntity(Q1Entity<Scale287>& entity);
};

class Scale288Map {
public:
    static void ConfigureEntity(Q1Entity<Scale288>& entity);
};

class Scale289Map {
public:
    static void ConfigureEntity(Q1Entity<Scale289>& entity);
};

class Scale290Map {
public:
    static void ConfigureEntity(Q1Entity<Scale290>& entity);
};

class Scale291Map {
public:
    static void ConfigureEntity(Q1Entity<Scale291>& entity);
};

class Scale292Map {
public:
    static void ConfigureEntity(Q1Entity<Scale292>& entity);
};

class Scale293Map {
public:
    static void ConfigureEntity(Q1Entity<Scale293>& entity);
};

class Scale294Map {
public:
    static void ConfigureEntity(Q1Entity<Scale294>& entity);
};

class Scale295Map {
public:
    static void ConfigureEntity(Q1Entity<Scale295>& entity);
};

class Scale296Map {
public:
    static void ConfigureEntity(Q1Entity<Scale296>& entity);
};

class Scale297Map {
public:
    static void ConfigureEntity(Q1Entity<Scale297>& entity);
};

class Scale298Map {
public:
    static void ConfigureEntity(Q1Entity<Scale298>& entity);
};

class Scale299Map {
public:
    static void ConfigureEntity(Q1Entity<Scale299>& entity);
};

} // namespace SchemaScale
