// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale080Map::ConfigureEntity(Q1Entity<Scale080>& entity) {
    entity.ToTableName("scale_080");
    entity.HasKey<&Scale080::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale080::name>().IsRequired();
    entity.Property<&Scale080::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale080::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale081Map::ConfigureEntity(Q1Entity<Scale081>& entity) {
    entity.ToTableName("scale_081");
    entity.HasKey<&Scale081::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale081::name>().IsRequired();
    entity.Property<&Scale081::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale081::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale082Map::ConfigureEntity(Q1Entity<Scale082>& entity) {
    entity.ToTableName("scale_082");
    entity.HasKey<&Scale082::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale082::name>().IsRequired();
    entity.Property<&Scale082::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale082::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale083Map::ConfigureEntity(Q1Entity<Scale083>& entity) {
    entity.ToTableName("scale_083");
    entity.HasKey<&Scale083::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale083::name>().IsRequired();
    entity.Property<&Scale083::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale083::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale084Map::ConfigureEntity(Q1Entity<Scale084>& entity) {
    entity.ToTableName("scale_084");
    entity.HasKey<&Scale084::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale084::name>().IsRequired();
    entity.Property<&Scale084::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale084::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale085Map::ConfigureEntity(Q1Entity<Scale085>& entity) {
    entity.ToTableName("scale_085");
    entity.HasKey<&Scale085::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale085::name>().IsRequired();
    entity.Property<&Scale085::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale085::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale086Map::ConfigureEntity(Q1Entity<Scale086>& entity) {
    entity.ToTableName("scale_086");
    entity.HasKey<&Scale086::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale086::name>().IsRequired();
    entity.Property<&Scale086::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale086::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale087Map::ConfigureEntity(Q1Entity<Scale087>& entity) {
    entity.ToTableName("scale_087");
    entity.HasKey<&Scale087::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale087::name>().IsRequired();
    entity.Property<&Scale087::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale087::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale088Map::ConfigureEntity(Q1Entity<Scale088>& entity) {
    entity.ToTableName("scale_088");
    entity.HasKey<&Scale088::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale088::name>().IsRequired();
    entity.Property<&Scale088::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale088::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale089Map::ConfigureEntity(Q1Entity<Scale089>& entity) {
    entity.ToTableName("scale_089");
    entity.HasKey<&Scale089::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale089::name>().IsRequired();
    entity.Property<&Scale089::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale089::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale090Map::ConfigureEntity(Q1Entity<Scale090>& entity) {
    entity.ToTableName("scale_090");
    entity.HasKey<&Scale090::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale090::name>().IsRequired();
    entity.Property<&Scale090::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale090::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale091Map::ConfigureEntity(Q1Entity<Scale091>& entity) {
    entity.ToTableName("scale_091");
    entity.HasKey<&Scale091::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale091::name>().IsRequired();
    entity.Property<&Scale091::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale091::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale092Map::ConfigureEntity(Q1Entity<Scale092>& entity) {
    entity.ToTableName("scale_092");
    entity.HasKey<&Scale092::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale092::name>().IsRequired();
    entity.Property<&Scale092::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale092::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale093Map::ConfigureEntity(Q1Entity<Scale093>& entity) {
    entity.ToTableName("scale_093");
    entity.HasKey<&Scale093::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale093::name>().IsRequired();
    entity.Property<&Scale093::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale093::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale094Map::ConfigureEntity(Q1Entity<Scale094>& entity) {
    entity.ToTableName("scale_094");
    entity.HasKey<&Scale094::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale094::name>().IsRequired();
    entity.Property<&Scale094::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale094::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale095Map::ConfigureEntity(Q1Entity<Scale095>& entity) {
    entity.ToTableName("scale_095");
    entity.HasKey<&Scale095::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale095::name>().IsRequired();
    entity.Property<&Scale095::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale095::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale096Map::ConfigureEntity(Q1Entity<Scale096>& entity) {
    entity.ToTableName("scale_096");
    entity.HasKey<&Scale096::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale096::name>().IsRequired();
    entity.Property<&Scale096::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale096::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale097Map::ConfigureEntity(Q1Entity<Scale097>& entity) {
    entity.ToTableName("scale_097");
    entity.HasKey<&Scale097::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale097::name>().IsRequired();
    entity.Property<&Scale097::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale097::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale098Map::ConfigureEntity(Q1Entity<Scale098>& entity) {
    entity.ToTableName("scale_098");
    entity.HasKey<&Scale098::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale098::name>().IsRequired();
    entity.Property<&Scale098::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale098::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale099Map::ConfigureEntity(Q1Entity<Scale099>& entity) {
    entity.ToTableName("scale_099");
    entity.HasKey<&Scale099::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale099::name>().IsRequired();
    entity.Property<&Scale099::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale099::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup04() {
    if (!InsertTableRows(scale080, 80)) return false;
    if (!InsertTableRows(scale081, 81)) return false;
    if (!InsertTableRows(scale082, 82)) return false;
    if (!InsertTableRows(scale083, 83)) return false;
    if (!InsertTableRows(scale084, 84)) return false;
    if (!InsertTableRows(scale085, 85)) return false;
    if (!InsertTableRows(scale086, 86)) return false;
    if (!InsertTableRows(scale087, 87)) return false;
    if (!InsertTableRows(scale088, 88)) return false;
    if (!InsertTableRows(scale089, 89)) return false;
    if (!InsertTableRows(scale090, 90)) return false;
    if (!InsertTableRows(scale091, 91)) return false;
    if (!InsertTableRows(scale092, 92)) return false;
    if (!InsertTableRows(scale093, 93)) return false;
    if (!InsertTableRows(scale094, 94)) return false;
    if (!InsertTableRows(scale095, 95)) return false;
    if (!InsertTableRows(scale096, 96)) return false;
    if (!InsertTableRows(scale097, 97)) return false;
    if (!InsertTableRows(scale098, 98)) return false;
    if (!InsertTableRows(scale099, 99)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup04() {
    scale080.Property<&Scale080::revision>().IsRequired();
    scale080.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale081.Property<&Scale081::revision>().IsRequired();
    scale081.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale082.Property<&Scale082::revision>().IsRequired();
    scale082.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale083.Property<&Scale083::revision>().IsRequired();
    scale083.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale084.Property<&Scale084::revision>().IsRequired();
    scale084.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale085.Property<&Scale085::revision>().IsRequired();
    scale085.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale086.Property<&Scale086::revision>().IsRequired();
    scale086.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale087.Property<&Scale087::revision>().IsRequired();
    scale087.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale088.Property<&Scale088::revision>().IsRequired();
    scale088.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale089.Property<&Scale089::revision>().IsRequired();
    scale089.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale090.Property<&Scale090::revision>().IsRequired();
    scale090.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale091.Property<&Scale091::revision>().IsRequired();
    scale091.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale092.Property<&Scale092::revision>().IsRequired();
    scale092.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale093.Property<&Scale093::revision>().IsRequired();
    scale093.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale094.Property<&Scale094::revision>().IsRequired();
    scale094.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale095.Property<&Scale095::revision>().IsRequired();
    scale095.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale096.Property<&Scale096::revision>().IsRequired();
    scale096.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale097.Property<&Scale097::revision>().IsRequired();
    scale097.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale098.Property<&Scale098::revision>().IsRequired();
    scale098.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale099.Property<&Scale099::revision>().IsRequired();
    scale099.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
