// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale160Map::ConfigureEntity(Q1Entity<Scale160>& entity) {
    entity.ToTableName("scale_160");
    entity.HasKey<&Scale160::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale160::name>().IsRequired();
    entity.Property<&Scale160::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale160::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale161Map::ConfigureEntity(Q1Entity<Scale161>& entity) {
    entity.ToTableName("scale_161");
    entity.HasKey<&Scale161::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale161::name>().IsRequired();
    entity.Property<&Scale161::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale161::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale162Map::ConfigureEntity(Q1Entity<Scale162>& entity) {
    entity.ToTableName("scale_162");
    entity.HasKey<&Scale162::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale162::name>().IsRequired();
    entity.Property<&Scale162::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale162::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale163Map::ConfigureEntity(Q1Entity<Scale163>& entity) {
    entity.ToTableName("scale_163");
    entity.HasKey<&Scale163::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale163::name>().IsRequired();
    entity.Property<&Scale163::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale163::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale164Map::ConfigureEntity(Q1Entity<Scale164>& entity) {
    entity.ToTableName("scale_164");
    entity.HasKey<&Scale164::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale164::name>().IsRequired();
    entity.Property<&Scale164::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale164::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale165Map::ConfigureEntity(Q1Entity<Scale165>& entity) {
    entity.ToTableName("scale_165");
    entity.HasKey<&Scale165::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale165::name>().IsRequired();
    entity.Property<&Scale165::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale165::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale166Map::ConfigureEntity(Q1Entity<Scale166>& entity) {
    entity.ToTableName("scale_166");
    entity.HasKey<&Scale166::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale166::name>().IsRequired();
    entity.Property<&Scale166::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale166::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale167Map::ConfigureEntity(Q1Entity<Scale167>& entity) {
    entity.ToTableName("scale_167");
    entity.HasKey<&Scale167::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale167::name>().IsRequired();
    entity.Property<&Scale167::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale167::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale168Map::ConfigureEntity(Q1Entity<Scale168>& entity) {
    entity.ToTableName("scale_168");
    entity.HasKey<&Scale168::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale168::name>().IsRequired();
    entity.Property<&Scale168::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale168::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale169Map::ConfigureEntity(Q1Entity<Scale169>& entity) {
    entity.ToTableName("scale_169");
    entity.HasKey<&Scale169::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale169::name>().IsRequired();
    entity.Property<&Scale169::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale169::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale170Map::ConfigureEntity(Q1Entity<Scale170>& entity) {
    entity.ToTableName("scale_170");
    entity.HasKey<&Scale170::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale170::name>().IsRequired();
    entity.Property<&Scale170::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale170::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale171Map::ConfigureEntity(Q1Entity<Scale171>& entity) {
    entity.ToTableName("scale_171");
    entity.HasKey<&Scale171::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale171::name>().IsRequired();
    entity.Property<&Scale171::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale171::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale172Map::ConfigureEntity(Q1Entity<Scale172>& entity) {
    entity.ToTableName("scale_172");
    entity.HasKey<&Scale172::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale172::name>().IsRequired();
    entity.Property<&Scale172::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale172::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale173Map::ConfigureEntity(Q1Entity<Scale173>& entity) {
    entity.ToTableName("scale_173");
    entity.HasKey<&Scale173::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale173::name>().IsRequired();
    entity.Property<&Scale173::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale173::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale174Map::ConfigureEntity(Q1Entity<Scale174>& entity) {
    entity.ToTableName("scale_174");
    entity.HasKey<&Scale174::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale174::name>().IsRequired();
    entity.Property<&Scale174::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale174::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale175Map::ConfigureEntity(Q1Entity<Scale175>& entity) {
    entity.ToTableName("scale_175");
    entity.HasKey<&Scale175::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale175::name>().IsRequired();
    entity.Property<&Scale175::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale175::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale176Map::ConfigureEntity(Q1Entity<Scale176>& entity) {
    entity.ToTableName("scale_176");
    entity.HasKey<&Scale176::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale176::name>().IsRequired();
    entity.Property<&Scale176::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale176::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale177Map::ConfigureEntity(Q1Entity<Scale177>& entity) {
    entity.ToTableName("scale_177");
    entity.HasKey<&Scale177::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale177::name>().IsRequired();
    entity.Property<&Scale177::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale177::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale178Map::ConfigureEntity(Q1Entity<Scale178>& entity) {
    entity.ToTableName("scale_178");
    entity.HasKey<&Scale178::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale178::name>().IsRequired();
    entity.Property<&Scale178::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale178::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale179Map::ConfigureEntity(Q1Entity<Scale179>& entity) {
    entity.ToTableName("scale_179");
    entity.HasKey<&Scale179::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale179::name>().IsRequired();
    entity.Property<&Scale179::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale179::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup08() {
    if (!InsertTableRows(scale160, 160)) return false;
    if (!InsertTableRows(scale161, 161)) return false;
    if (!InsertTableRows(scale162, 162)) return false;
    if (!InsertTableRows(scale163, 163)) return false;
    if (!InsertTableRows(scale164, 164)) return false;
    if (!InsertTableRows(scale165, 165)) return false;
    if (!InsertTableRows(scale166, 166)) return false;
    if (!InsertTableRows(scale167, 167)) return false;
    if (!InsertTableRows(scale168, 168)) return false;
    if (!InsertTableRows(scale169, 169)) return false;
    if (!InsertTableRows(scale170, 170)) return false;
    if (!InsertTableRows(scale171, 171)) return false;
    if (!InsertTableRows(scale172, 172)) return false;
    if (!InsertTableRows(scale173, 173)) return false;
    if (!InsertTableRows(scale174, 174)) return false;
    if (!InsertTableRows(scale175, 175)) return false;
    if (!InsertTableRows(scale176, 176)) return false;
    if (!InsertTableRows(scale177, 177)) return false;
    if (!InsertTableRows(scale178, 178)) return false;
    if (!InsertTableRows(scale179, 179)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup08() {
    scale160.Property<&Scale160::revision>().IsRequired();
    scale160.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale161.Property<&Scale161::revision>().IsRequired();
    scale161.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale162.Property<&Scale162::revision>().IsRequired();
    scale162.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale163.Property<&Scale163::revision>().IsRequired();
    scale163.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale164.Property<&Scale164::revision>().IsRequired();
    scale164.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale165.Property<&Scale165::revision>().IsRequired();
    scale165.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale166.Property<&Scale166::revision>().IsRequired();
    scale166.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale167.Property<&Scale167::revision>().IsRequired();
    scale167.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale168.Property<&Scale168::revision>().IsRequired();
    scale168.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale169.Property<&Scale169::revision>().IsRequired();
    scale169.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale170.Property<&Scale170::revision>().IsRequired();
    scale170.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale171.Property<&Scale171::revision>().IsRequired();
    scale171.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale172.Property<&Scale172::revision>().IsRequired();
    scale172.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale173.Property<&Scale173::revision>().IsRequired();
    scale173.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale174.Property<&Scale174::revision>().IsRequired();
    scale174.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale175.Property<&Scale175::revision>().IsRequired();
    scale175.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale176.Property<&Scale176::revision>().IsRequired();
    scale176.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale177.Property<&Scale177::revision>().IsRequired();
    scale177.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale178.Property<&Scale178::revision>().IsRequired();
    scale178.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale179.Property<&Scale179::revision>().IsRequired();
    scale179.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
