// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale280Map::ConfigureEntity(Q1Entity<Scale280>& entity) {
    entity.ToTableName("scale_280");
    entity.HasKey<&Scale280::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale280::name>().IsRequired();
    entity.Property<&Scale280::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale280::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale281Map::ConfigureEntity(Q1Entity<Scale281>& entity) {
    entity.ToTableName("scale_281");
    entity.HasKey<&Scale281::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale281::name>().IsRequired();
    entity.Property<&Scale281::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale281::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale282Map::ConfigureEntity(Q1Entity<Scale282>& entity) {
    entity.ToTableName("scale_282");
    entity.HasKey<&Scale282::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale282::name>().IsRequired();
    entity.Property<&Scale282::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale282::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale283Map::ConfigureEntity(Q1Entity<Scale283>& entity) {
    entity.ToTableName("scale_283");
    entity.HasKey<&Scale283::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale283::name>().IsRequired();
    entity.Property<&Scale283::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale283::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale284Map::ConfigureEntity(Q1Entity<Scale284>& entity) {
    entity.ToTableName("scale_284");
    entity.HasKey<&Scale284::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale284::name>().IsRequired();
    entity.Property<&Scale284::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale284::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale285Map::ConfigureEntity(Q1Entity<Scale285>& entity) {
    entity.ToTableName("scale_285");
    entity.HasKey<&Scale285::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale285::name>().IsRequired();
    entity.Property<&Scale285::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale285::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale286Map::ConfigureEntity(Q1Entity<Scale286>& entity) {
    entity.ToTableName("scale_286");
    entity.HasKey<&Scale286::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale286::name>().IsRequired();
    entity.Property<&Scale286::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale286::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale287Map::ConfigureEntity(Q1Entity<Scale287>& entity) {
    entity.ToTableName("scale_287");
    entity.HasKey<&Scale287::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale287::name>().IsRequired();
    entity.Property<&Scale287::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale287::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale288Map::ConfigureEntity(Q1Entity<Scale288>& entity) {
    entity.ToTableName("scale_288");
    entity.HasKey<&Scale288::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale288::name>().IsRequired();
    entity.Property<&Scale288::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale288::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale289Map::ConfigureEntity(Q1Entity<Scale289>& entity) {
    entity.ToTableName("scale_289");
    entity.HasKey<&Scale289::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale289::name>().IsRequired();
    entity.Property<&Scale289::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale289::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale290Map::ConfigureEntity(Q1Entity<Scale290>& entity) {
    entity.ToTableName("scale_290");
    entity.HasKey<&Scale290::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale290::name>().IsRequired();
    entity.Property<&Scale290::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale290::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale291Map::ConfigureEntity(Q1Entity<Scale291>& entity) {
    entity.ToTableName("scale_291");
    entity.HasKey<&Scale291::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale291::name>().IsRequired();
    entity.Property<&Scale291::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale291::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale292Map::ConfigureEntity(Q1Entity<Scale292>& entity) {
    entity.ToTableName("scale_292");
    entity.HasKey<&Scale292::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale292::name>().IsRequired();
    entity.Property<&Scale292::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale292::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale293Map::ConfigureEntity(Q1Entity<Scale293>& entity) {
    entity.ToTableName("scale_293");
    entity.HasKey<&Scale293::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale293::name>().IsRequired();
    entity.Property<&Scale293::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale293::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale294Map::ConfigureEntity(Q1Entity<Scale294>& entity) {
    entity.ToTableName("scale_294");
    entity.HasKey<&Scale294::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale294::name>().IsRequired();
    entity.Property<&Scale294::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale294::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale295Map::ConfigureEntity(Q1Entity<Scale295>& entity) {
    entity.ToTableName("scale_295");
    entity.HasKey<&Scale295::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale295::name>().IsRequired();
    entity.Property<&Scale295::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale295::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale296Map::ConfigureEntity(Q1Entity<Scale296>& entity) {
    entity.ToTableName("scale_296");
    entity.HasKey<&Scale296::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale296::name>().IsRequired();
    entity.Property<&Scale296::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale296::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale297Map::ConfigureEntity(Q1Entity<Scale297>& entity) {
    entity.ToTableName("scale_297");
    entity.HasKey<&Scale297::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale297::name>().IsRequired();
    entity.Property<&Scale297::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale297::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale298Map::ConfigureEntity(Q1Entity<Scale298>& entity) {
    entity.ToTableName("scale_298");
    entity.HasKey<&Scale298::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale298::name>().IsRequired();
    entity.Property<&Scale298::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale298::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale299Map::ConfigureEntity(Q1Entity<Scale299>& entity) {
    entity.ToTableName("scale_299");
    entity.HasKey<&Scale299::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale299::name>().IsRequired();
    entity.Property<&Scale299::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale299::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup14() {
    if (!InsertTableRows(scale280, 280)) return false;
    if (!InsertTableRows(scale281, 281)) return false;
    if (!InsertTableRows(scale282, 282)) return false;
    if (!InsertTableRows(scale283, 283)) return false;
    if (!InsertTableRows(scale284, 284)) return false;
    if (!InsertTableRows(scale285, 285)) return false;
    if (!InsertTableRows(scale286, 286)) return false;
    if (!InsertTableRows(scale287, 287)) return false;
    if (!InsertTableRows(scale288, 288)) return false;
    if (!InsertTableRows(scale289, 289)) return false;
    if (!InsertTableRows(scale290, 290)) return false;
    if (!InsertTableRows(scale291, 291)) return false;
    if (!InsertTableRows(scale292, 292)) return false;
    if (!InsertTableRows(scale293, 293)) return false;
    if (!InsertTableRows(scale294, 294)) return false;
    if (!InsertTableRows(scale295, 295)) return false;
    if (!InsertTableRows(scale296, 296)) return false;
    if (!InsertTableRows(scale297, 297)) return false;
    if (!InsertTableRows(scale298, 298)) return false;
    if (!InsertTableRows(scale299, 299)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup14() {
    scale280.Property<&Scale280::revision>().IsRequired();
    scale280.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale281.Property<&Scale281::revision>().IsRequired();
    scale281.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale282.Property<&Scale282::revision>().IsRequired();
    scale282.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale283.Property<&Scale283::revision>().IsRequired();
    scale283.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale284.Property<&Scale284::revision>().IsRequired();
    scale284.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale285.Property<&Scale285::revision>().IsRequired();
    scale285.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale286.Property<&Scale286::revision>().IsRequired();
    scale286.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale287.Property<&Scale287::revision>().IsRequired();
    scale287.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale288.Property<&Scale288::revision>().IsRequired();
    scale288.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale289.Property<&Scale289::revision>().IsRequired();
    scale289.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale290.Property<&Scale290::revision>().IsRequired();
    scale290.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale291.Property<&Scale291::revision>().IsRequired();
    scale291.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale292.Property<&Scale292::revision>().IsRequired();
    scale292.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale293.Property<&Scale293::revision>().IsRequired();
    scale293.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale294.Property<&Scale294::revision>().IsRequired();
    scale294.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale295.Property<&Scale295::revision>().IsRequired();
    scale295.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale296.Property<&Scale296::revision>().IsRequired();
    scale296.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale297.Property<&Scale297::revision>().IsRequired();
    scale297.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale298.Property<&Scale298::revision>().IsRequired();
    scale298.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale299.Property<&Scale299::revision>().IsRequired();
    scale299.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
