// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale000Map::ConfigureEntity(Q1Entity<Scale000>& entity) {
    entity.ToTableName("scale_000");
    entity.HasKey<&Scale000::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale000::name>().IsRequired();
    entity.Property<&Scale000::parent_id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale001Map::ConfigureEntity(Q1Entity<Scale001>& entity) {
    entity.ToTableName("scale_001");
    entity.HasKey<&Scale001::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale001::name>().IsRequired();
    entity.Property<&Scale001::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale001::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale002Map::ConfigureEntity(Q1Entity<Scale002>& entity) {
    entity.ToTableName("scale_002");
    entity.HasKey<&Scale002::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale002::name>().IsRequired();
    entity.Property<&Scale002::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale002::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale003Map::ConfigureEntity(Q1Entity<Scale003>& entity) {
    entity.ToTableName("scale_003");
    entity.HasKey<&Scale003::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale003::name>().IsRequired();
    entity.Property<&Scale003::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale003::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale004Map::ConfigureEntity(Q1Entity<Scale004>& entity) {
    entity.ToTableName("scale_004");
    entity.HasKey<&Scale004::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale004::name>().IsRequired();
    entity.Property<&Scale004::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale004::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale005Map::ConfigureEntity(Q1Entity<Scale005>& entity) {
    entity.ToTableName("scale_005");
    entity.HasKey<&Scale005::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale005::name>().IsRequired();
    entity.Property<&Scale005::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale005::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale006Map::ConfigureEntity(Q1Entity<Scale006>& entity) {
    entity.ToTableName("scale_006");
    entity.HasKey<&Scale006::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale006::name>().IsRequired();
    entity.Property<&Scale006::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale006::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale007Map::ConfigureEntity(Q1Entity<Scale007>& entity) {
    entity.ToTableName("scale_007");
    entity.HasKey<&Scale007::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale007::name>().IsRequired();
    entity.Property<&Scale007::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale007::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale008Map::ConfigureEntity(Q1Entity<Scale008>& entity) {
    entity.ToTableName("scale_008");
    entity.HasKey<&Scale008::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale008::name>().IsRequired();
    entity.Property<&Scale008::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale008::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale009Map::ConfigureEntity(Q1Entity<Scale009>& entity) {
    entity.ToTableName("scale_009");
    entity.HasKey<&Scale009::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale009::name>().IsRequired();
    entity.Property<&Scale009::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale009::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale010Map::ConfigureEntity(Q1Entity<Scale010>& entity) {
    entity.ToTableName("scale_010");
    entity.HasKey<&Scale010::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale010::name>().IsRequired();
    entity.Property<&Scale010::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale010::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale011Map::ConfigureEntity(Q1Entity<Scale011>& entity) {
    entity.ToTableName("scale_011");
    entity.HasKey<&Scale011::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale011::name>().IsRequired();
    entity.Property<&Scale011::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale011::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale012Map::ConfigureEntity(Q1Entity<Scale012>& entity) {
    entity.ToTableName("scale_012");
    entity.HasKey<&Scale012::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale012::name>().IsRequired();
    entity.Property<&Scale012::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale012::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale013Map::ConfigureEntity(Q1Entity<Scale013>& entity) {
    entity.ToTableName("scale_013");
    entity.HasKey<&Scale013::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale013::name>().IsRequired();
    entity.Property<&Scale013::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale013::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale014Map::ConfigureEntity(Q1Entity<Scale014>& entity) {
    entity.ToTableName("scale_014");
    entity.HasKey<&Scale014::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale014::name>().IsRequired();
    entity.Property<&Scale014::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale014::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale015Map::ConfigureEntity(Q1Entity<Scale015>& entity) {
    entity.ToTableName("scale_015");
    entity.HasKey<&Scale015::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale015::name>().IsRequired();
    entity.Property<&Scale015::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale015::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale016Map::ConfigureEntity(Q1Entity<Scale016>& entity) {
    entity.ToTableName("scale_016");
    entity.HasKey<&Scale016::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale016::name>().IsRequired();
    entity.Property<&Scale016::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale016::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale017Map::ConfigureEntity(Q1Entity<Scale017>& entity) {
    entity.ToTableName("scale_017");
    entity.HasKey<&Scale017::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale017::name>().IsRequired();
    entity.Property<&Scale017::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale017::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale018Map::ConfigureEntity(Q1Entity<Scale018>& entity) {
    entity.ToTableName("scale_018");
    entity.HasKey<&Scale018::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale018::name>().IsRequired();
    entity.Property<&Scale018::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale018::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale019Map::ConfigureEntity(Q1Entity<Scale019>& entity) {
    entity.ToTableName("scale_019");
    entity.HasKey<&Scale019::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale019::name>().IsRequired();
    entity.Property<&Scale019::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale019::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup00() {
    if (!InsertTableRows(scale000, 0)) return false;
    if (!InsertTableRows(scale001, 1)) return false;
    if (!InsertTableRows(scale002, 2)) return false;
    if (!InsertTableRows(scale003, 3)) return false;
    if (!InsertTableRows(scale004, 4)) return false;
    if (!InsertTableRows(scale005, 5)) return false;
    if (!InsertTableRows(scale006, 6)) return false;
    if (!InsertTableRows(scale007, 7)) return false;
    if (!InsertTableRows(scale008, 8)) return false;
    if (!InsertTableRows(scale009, 9)) return false;
    if (!InsertTableRows(scale010, 10)) return false;
    if (!InsertTableRows(scale011, 11)) return false;
    if (!InsertTableRows(scale012, 12)) return false;
    if (!InsertTableRows(scale013, 13)) return false;
    if (!InsertTableRows(scale014, 14)) return false;
    if (!InsertTableRows(scale015, 15)) return false;
    if (!InsertTableRows(scale016, 16)) return false;
    if (!InsertTableRows(scale017, 17)) return false;
    if (!InsertTableRows(scale018, 18)) return false;
    if (!InsertTableRows(scale019, 19)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup00() {
    scale000.Property<&Scale000::revision>().IsRequired();
    scale000.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale001.Property<&Scale001::revision>().IsRequired();
    scale001.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale002.Property<&Scale002::revision>().IsRequired();
    scale002.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale003.Property<&Scale003::revision>().IsRequired();
    scale003.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale004.Property<&Scale004::revision>().IsRequired();
    scale004.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale005.Property<&Scale005::revision>().IsRequired();
    scale005.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale006.Property<&Scale006::revision>().IsRequired();
    scale006.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale007.Property<&Scale007::revision>().IsRequired();
    scale007.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale008.Property<&Scale008::revision>().IsRequired();
    scale008.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale009.Property<&Scale009::revision>().IsRequired();
    scale009.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale010.Property<&Scale010::revision>().IsRequired();
    scale010.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale011.Property<&Scale011::revision>().IsRequired();
    scale011.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale012.Property<&Scale012::revision>().IsRequired();
    scale012.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale013.Property<&Scale013::revision>().IsRequired();
    scale013.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale014.Property<&Scale014::revision>().IsRequired();
    scale014.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale015.Property<&Scale015::revision>().IsRequired();
    scale015.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale016.Property<&Scale016::revision>().IsRequired();
    scale016.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale017.Property<&Scale017::revision>().IsRequired();
    scale017.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale018.Property<&Scale018::revision>().IsRequired();
    scale018.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale019.Property<&Scale019::revision>().IsRequired();
    scale019.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
