// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale180Map::ConfigureEntity(Q1Entity<Scale180>& entity) {
    entity.ToTableName("scale_180");
    entity.HasKey<&Scale180::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale180::name>().IsRequired();
    entity.Property<&Scale180::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale180::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale181Map::ConfigureEntity(Q1Entity<Scale181>& entity) {
    entity.ToTableName("scale_181");
    entity.HasKey<&Scale181::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale181::name>().IsRequired();
    entity.Property<&Scale181::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale181::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale182Map::ConfigureEntity(Q1Entity<Scale182>& entity) {
    entity.ToTableName("scale_182");
    entity.HasKey<&Scale182::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale182::name>().IsRequired();
    entity.Property<&Scale182::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale182::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale183Map::ConfigureEntity(Q1Entity<Scale183>& entity) {
    entity.ToTableName("scale_183");
    entity.HasKey<&Scale183::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale183::name>().IsRequired();
    entity.Property<&Scale183::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale183::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale184Map::ConfigureEntity(Q1Entity<Scale184>& entity) {
    entity.ToTableName("scale_184");
    entity.HasKey<&Scale184::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale184::name>().IsRequired();
    entity.Property<&Scale184::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale184::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale185Map::ConfigureEntity(Q1Entity<Scale185>& entity) {
    entity.ToTableName("scale_185");
    entity.HasKey<&Scale185::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale185::name>().IsRequired();
    entity.Property<&Scale185::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale185::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale186Map::ConfigureEntity(Q1Entity<Scale186>& entity) {
    entity.ToTableName("scale_186");
    entity.HasKey<&Scale186::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale186::name>().IsRequired();
    entity.Property<&Scale186::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale186::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale187Map::ConfigureEntity(Q1Entity<Scale187>& entity) {
    entity.ToTableName("scale_187");
    entity.HasKey<&Scale187::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale187::name>().IsRequired();
    entity.Property<&Scale187::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale187::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale188Map::ConfigureEntity(Q1Entity<Scale188>& entity) {
    entity.ToTableName("scale_188");
    entity.HasKey<&Scale188::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale188::name>().IsRequired();
    entity.Property<&Scale188::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale188::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale189Map::ConfigureEntity(Q1Entity<Scale189>& entity) {
    entity.ToTableName("scale_189");
    entity.HasKey<&Scale189::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale189::name>().IsRequired();
    entity.Property<&Scale189::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale189::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale190Map::ConfigureEntity(Q1Entity<Scale190>& entity) {
    entity.ToTableName("scale_190");
    entity.HasKey<&Scale190::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale190::name>().IsRequired();
    entity.Property<&Scale190::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale190::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale191Map::ConfigureEntity(Q1Entity<Scale191>& entity) {
    entity.ToTableName("scale_191");
    entity.HasKey<&Scale191::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale191::name>().IsRequired();
    entity.Property<&Scale191::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale191::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale192Map::ConfigureEntity(Q1Entity<Scale192>& entity) {
    entity.ToTableName("scale_192");
    entity.HasKey<&Scale192::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale192::name>().IsRequired();
    entity.Property<&Scale192::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale192::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale193Map::ConfigureEntity(Q1Entity<Scale193>& entity) {
    entity.ToTableName("scale_193");
    entity.HasKey<&Scale193::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale193::name>().IsRequired();
    entity.Property<&Scale193::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale193::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale194Map::ConfigureEntity(Q1Entity<Scale194>& entity) {
    entity.ToTableName("scale_194");
    entity.HasKey<&Scale194::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale194::name>().IsRequired();
    entity.Property<&Scale194::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale194::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale195Map::ConfigureEntity(Q1Entity<Scale195>& entity) {
    entity.ToTableName("scale_195");
    entity.HasKey<&Scale195::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale195::name>().IsRequired();
    entity.Property<&Scale195::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale195::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale196Map::ConfigureEntity(Q1Entity<Scale196>& entity) {
    entity.ToTableName("scale_196");
    entity.HasKey<&Scale196::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale196::name>().IsRequired();
    entity.Property<&Scale196::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale196::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale197Map::ConfigureEntity(Q1Entity<Scale197>& entity) {
    entity.ToTableName("scale_197");
    entity.HasKey<&Scale197::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale197::name>().IsRequired();
    entity.Property<&Scale197::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale197::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale198Map::ConfigureEntity(Q1Entity<Scale198>& entity) {
    entity.ToTableName("scale_198");
    entity.HasKey<&Scale198::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale198::name>().IsRequired();
    entity.Property<&Scale198::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale198::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale199Map::ConfigureEntity(Q1Entity<Scale199>& entity) {
    entity.ToTableName("scale_199");
    entity.HasKey<&Scale199::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale199::name>().IsRequired();
    entity.Property<&Scale199::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale199::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup09() {
    if (!InsertTableRows(scale180, 180)) return false;
    if (!InsertTableRows(scale181, 181)) return false;
    if (!InsertTableRows(scale182, 182)) return false;
    if (!InsertTableRows(scale183, 183)) return false;
    if (!InsertTableRows(scale184, 184)) return false;
    if (!InsertTableRows(scale185, 185)) return false;
    if (!InsertTableRows(scale186, 186)) return false;
    if (!InsertTableRows(scale187, 187)) return false;
    if (!InsertTableRows(scale188, 188)) return false;
    if (!InsertTableRows(scale189, 189)) return false;
    if (!InsertTableRows(scale190, 190)) return false;
    if (!InsertTableRows(scale191, 191)) return false;
    if (!InsertTableRows(scale192, 192)) return false;
    if (!InsertTableRows(scale193, 193)) return false;
    if (!InsertTableRows(scale194, 194)) return false;
    if (!InsertTableRows(scale195, 195)) return false;
    if (!InsertTableRows(scale196, 196)) return false;
    if (!InsertTableRows(scale197, 197)) return false;
    if (!InsertTableRows(scale198, 198)) return false;
    if (!InsertTableRows(scale199, 199)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup09() {
    scale180.Property<&Scale180::revision>().IsRequired();
    scale180.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale181.Property<&Scale181::revision>().IsRequired();
    scale181.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale182.Property<&Scale182::revision>().IsRequired();
    scale182.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale183.Property<&Scale183::revision>().IsRequired();
    scale183.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale184.Property<&Scale184::revision>().IsRequired();
    scale184.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale185.Property<&Scale185::revision>().IsRequired();
    scale185.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale186.Property<&Scale186::revision>().IsRequired();
    scale186.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale187.Property<&Scale187::revision>().IsRequired();
    scale187.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale188.Property<&Scale188::revision>().IsRequired();
    scale188.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale189.Property<&Scale189::revision>().IsRequired();
    scale189.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale190.Property<&Scale190::revision>().IsRequired();
    scale190.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale191.Property<&Scale191::revision>().IsRequired();
    scale191.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale192.Property<&Scale192::revision>().IsRequired();
    scale192.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale193.Property<&Scale193::revision>().IsRequired();
    scale193.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale194.Property<&Scale194::revision>().IsRequired();
    scale194.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale195.Property<&Scale195::revision>().IsRequired();
    scale195.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale196.Property<&Scale196::revision>().IsRequired();
    scale196.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale197.Property<&Scale197::revision>().IsRequired();
    scale197.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale198.Property<&Scale198::revision>().IsRequired();
    scale198.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale199.Property<&Scale199::revision>().IsRequired();
    scale199.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
