// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale140Map::ConfigureEntity(Q1Entity<Scale140>& entity) {
    entity.ToTableName("scale_140");
    entity.HasKey<&Scale140::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale140::name>().IsRequired();
    entity.Property<&Scale140::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale140::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale141Map::ConfigureEntity(Q1Entity<Scale141>& entity) {
    entity.ToTableName("scale_141");
    entity.HasKey<&Scale141::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale141::name>().IsRequired();
    entity.Property<&Scale141::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale141::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale142Map::ConfigureEntity(Q1Entity<Scale142>& entity) {
    entity.ToTableName("scale_142");
    entity.HasKey<&Scale142::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale142::name>().IsRequired();
    entity.Property<&Scale142::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale142::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale143Map::ConfigureEntity(Q1Entity<Scale143>& entity) {
    entity.ToTableName("scale_143");
    entity.HasKey<&Scale143::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale143::name>().IsRequired();
    entity.Property<&Scale143::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale143::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale144Map::ConfigureEntity(Q1Entity<Scale144>& entity) {
    entity.ToTableName("scale_144");
    entity.HasKey<&Scale144::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale144::name>().IsRequired();
    entity.Property<&Scale144::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale144::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale145Map::ConfigureEntity(Q1Entity<Scale145>& entity) {
    entity.ToTableName("scale_145");
    entity.HasKey<&Scale145::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale145::name>().IsRequired();
    entity.Property<&Scale145::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale145::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale146Map::ConfigureEntity(Q1Entity<Scale146>& entity) {
    entity.ToTableName("scale_146");
    entity.HasKey<&Scale146::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale146::name>().IsRequired();
    entity.Property<&Scale146::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale146::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale147Map::ConfigureEntity(Q1Entity<Scale147>& entity) {
    entity.ToTableName("scale_147");
    entity.HasKey<&Scale147::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale147::name>().IsRequired();
    entity.Property<&Scale147::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale147::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale148Map::ConfigureEntity(Q1Entity<Scale148>& entity) {
    entity.ToTableName("scale_148");
    entity.HasKey<&Scale148::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale148::name>().IsRequired();
    entity.Property<&Scale148::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale148::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale149Map::ConfigureEntity(Q1Entity<Scale149>& entity) {
    entity.ToTableName("scale_149");
    entity.HasKey<&Scale149::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale149::name>().IsRequired();
    entity.Property<&Scale149::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale149::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale150Map::ConfigureEntity(Q1Entity<Scale150>& entity) {
    entity.ToTableName("scale_150");
    entity.HasKey<&Scale150::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale150::name>().IsRequired();
    entity.Property<&Scale150::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale150::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale151Map::ConfigureEntity(Q1Entity<Scale151>& entity) {
    entity.ToTableName("scale_151");
    entity.HasKey<&Scale151::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale151::name>().IsRequired();
    entity.Property<&Scale151::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale151::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale152Map::ConfigureEntity(Q1Entity<Scale152>& entity) {
    entity.ToTableName("scale_152");
    entity.HasKey<&Scale152::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale152::name>().IsRequired();
    entity.Property<&Scale152::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale152::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale153Map::ConfigureEntity(Q1Entity<Scale153>& entity) {
    entity.ToTableName("scale_153");
    entity.HasKey<&Scale153::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale153::name>().IsRequired();
    entity.Property<&Scale153::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale153::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale154Map::ConfigureEntity(Q1Entity<Scale154>& entity) {
    entity.ToTableName("scale_154");
    entity.HasKey<&Scale154::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale154::name>().IsRequired();
    entity.Property<&Scale154::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale154::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale155Map::ConfigureEntity(Q1Entity<Scale155>& entity) {
    entity.ToTableName("scale_155");
    entity.HasKey<&Scale155::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale155::name>().IsRequired();
    entity.Property<&Scale155::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale155::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale156Map::ConfigureEntity(Q1Entity<Scale156>& entity) {
    entity.ToTableName("scale_156");
    entity.HasKey<&Scale156::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale156::name>().IsRequired();
    entity.Property<&Scale156::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale156::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale157Map::ConfigureEntity(Q1Entity<Scale157>& entity) {
    entity.ToTableName("scale_157");
    entity.HasKey<&Scale157::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale157::name>().IsRequired();
    entity.Property<&Scale157::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale157::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale158Map::ConfigureEntity(Q1Entity<Scale158>& entity) {
    entity.ToTableName("scale_158");
    entity.HasKey<&Scale158::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale158::name>().IsRequired();
    entity.Property<&Scale158::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale158::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale159Map::ConfigureEntity(Q1Entity<Scale159>& entity) {
    entity.ToTableName("scale_159");
    entity.HasKey<&Scale159::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale159::name>().IsRequired();
    entity.Property<&Scale159::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale159::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup07() {
    if (!InsertTableRows(scale140, 140)) return false;
    if (!InsertTableRows(scale141, 141)) return false;
    if (!InsertTableRows(scale142, 142)) return false;
    if (!InsertTableRows(scale143, 143)) return false;
    if (!InsertTableRows(scale144, 144)) return false;
    if (!InsertTableRows(scale145, 145)) return false;
    if (!InsertTableRows(scale146, 146)) return false;
    if (!InsertTableRows(scale147, 147)) return false;
    if (!InsertTableRows(scale148, 148)) return false;
    if (!InsertTableRows(scale149, 149)) return false;
    if (!InsertTableRows(scale150, 150)) return false;
    if (!InsertTableRows(scale151, 151)) return false;
    if (!InsertTableRows(scale152, 152)) return false;
    if (!InsertTableRows(scale153, 153)) return false;
    if (!InsertTableRows(scale154, 154)) return false;
    if (!InsertTableRows(scale155, 155)) return false;
    if (!InsertTableRows(scale156, 156)) return false;
    if (!InsertTableRows(scale157, 157)) return false;
    if (!InsertTableRows(scale158, 158)) return false;
    if (!InsertTableRows(scale159, 159)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup07() {
    scale140.Property<&Scale140::revision>().IsRequired();
    scale140.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale141.Property<&Scale141::revision>().IsRequired();
    scale141.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale142.Property<&Scale142::revision>().IsRequired();
    scale142.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale143.Property<&Scale143::revision>().IsRequired();
    scale143.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale144.Property<&Scale144::revision>().IsRequired();
    scale144.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale145.Property<&Scale145::revision>().IsRequired();
    scale145.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale146.Property<&Scale146::revision>().IsRequired();
    scale146.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale147.Property<&Scale147::revision>().IsRequired();
    scale147.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale148.Property<&Scale148::revision>().IsRequired();
    scale148.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale149.Property<&Scale149::revision>().IsRequired();
    scale149.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale150.Property<&Scale150::revision>().IsRequired();
    scale150.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale151.Property<&Scale151::revision>().IsRequired();
    scale151.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale152.Property<&Scale152::revision>().IsRequired();
    scale152.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale153.Property<&Scale153::revision>().IsRequired();
    scale153.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale154.Property<&Scale154::revision>().IsRequired();
    scale154.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale155.Property<&Scale155::revision>().IsRequired();
    scale155.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale156.Property<&Scale156::revision>().IsRequired();
    scale156.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale157.Property<&Scale157::revision>().IsRequired();
    scale157.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale158.Property<&Scale158::revision>().IsRequired();
    scale158.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale159.Property<&Scale159::revision>().IsRequired();
    scale159.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
