// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale120Map::ConfigureEntity(Q1Entity<Scale120>& entity) {
    entity.ToTableName("scale_120");
    entity.HasKey<&Scale120::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale120::name>().IsRequired();
    entity.Property<&Scale120::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale120::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale121Map::ConfigureEntity(Q1Entity<Scale121>& entity) {
    entity.ToTableName("scale_121");
    entity.HasKey<&Scale121::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale121::name>().IsRequired();
    entity.Property<&Scale121::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale121::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale122Map::ConfigureEntity(Q1Entity<Scale122>& entity) {
    entity.ToTableName("scale_122");
    entity.HasKey<&Scale122::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale122::name>().IsRequired();
    entity.Property<&Scale122::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale122::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale123Map::ConfigureEntity(Q1Entity<Scale123>& entity) {
    entity.ToTableName("scale_123");
    entity.HasKey<&Scale123::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale123::name>().IsRequired();
    entity.Property<&Scale123::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale123::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale124Map::ConfigureEntity(Q1Entity<Scale124>& entity) {
    entity.ToTableName("scale_124");
    entity.HasKey<&Scale124::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale124::name>().IsRequired();
    entity.Property<&Scale124::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale124::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale125Map::ConfigureEntity(Q1Entity<Scale125>& entity) {
    entity.ToTableName("scale_125");
    entity.HasKey<&Scale125::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale125::name>().IsRequired();
    entity.Property<&Scale125::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale125::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale126Map::ConfigureEntity(Q1Entity<Scale126>& entity) {
    entity.ToTableName("scale_126");
    entity.HasKey<&Scale126::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale126::name>().IsRequired();
    entity.Property<&Scale126::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale126::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale127Map::ConfigureEntity(Q1Entity<Scale127>& entity) {
    entity.ToTableName("scale_127");
    entity.HasKey<&Scale127::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale127::name>().IsRequired();
    entity.Property<&Scale127::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale127::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale128Map::ConfigureEntity(Q1Entity<Scale128>& entity) {
    entity.ToTableName("scale_128");
    entity.HasKey<&Scale128::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale128::name>().IsRequired();
    entity.Property<&Scale128::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale128::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale129Map::ConfigureEntity(Q1Entity<Scale129>& entity) {
    entity.ToTableName("scale_129");
    entity.HasKey<&Scale129::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale129::name>().IsRequired();
    entity.Property<&Scale129::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale129::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale130Map::ConfigureEntity(Q1Entity<Scale130>& entity) {
    entity.ToTableName("scale_130");
    entity.HasKey<&Scale130::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale130::name>().IsRequired();
    entity.Property<&Scale130::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale130::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale131Map::ConfigureEntity(Q1Entity<Scale131>& entity) {
    entity.ToTableName("scale_131");
    entity.HasKey<&Scale131::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale131::name>().IsRequired();
    entity.Property<&Scale131::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale131::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale132Map::ConfigureEntity(Q1Entity<Scale132>& entity) {
    entity.ToTableName("scale_132");
    entity.HasKey<&Scale132::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale132::name>().IsRequired();
    entity.Property<&Scale132::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale132::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale133Map::ConfigureEntity(Q1Entity<Scale133>& entity) {
    entity.ToTableName("scale_133");
    entity.HasKey<&Scale133::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale133::name>().IsRequired();
    entity.Property<&Scale133::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale133::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale134Map::ConfigureEntity(Q1Entity<Scale134>& entity) {
    entity.ToTableName("scale_134");
    entity.HasKey<&Scale134::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale134::name>().IsRequired();
    entity.Property<&Scale134::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale134::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale135Map::ConfigureEntity(Q1Entity<Scale135>& entity) {
    entity.ToTableName("scale_135");
    entity.HasKey<&Scale135::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale135::name>().IsRequired();
    entity.Property<&Scale135::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale135::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale136Map::ConfigureEntity(Q1Entity<Scale136>& entity) {
    entity.ToTableName("scale_136");
    entity.HasKey<&Scale136::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale136::name>().IsRequired();
    entity.Property<&Scale136::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale136::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale137Map::ConfigureEntity(Q1Entity<Scale137>& entity) {
    entity.ToTableName("scale_137");
    entity.HasKey<&Scale137::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale137::name>().IsRequired();
    entity.Property<&Scale137::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale137::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale138Map::ConfigureEntity(Q1Entity<Scale138>& entity) {
    entity.ToTableName("scale_138");
    entity.HasKey<&Scale138::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale138::name>().IsRequired();
    entity.Property<&Scale138::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale138::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale139Map::ConfigureEntity(Q1Entity<Scale139>& entity) {
    entity.ToTableName("scale_139");
    entity.HasKey<&Scale139::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale139::name>().IsRequired();
    entity.Property<&Scale139::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale139::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup06() {
    if (!InsertTableRows(scale120, 120)) return false;
    if (!InsertTableRows(scale121, 121)) return false;
    if (!InsertTableRows(scale122, 122)) return false;
    if (!InsertTableRows(scale123, 123)) return false;
    if (!InsertTableRows(scale124, 124)) return false;
    if (!InsertTableRows(scale125, 125)) return false;
    if (!InsertTableRows(scale126, 126)) return false;
    if (!InsertTableRows(scale127, 127)) return false;
    if (!InsertTableRows(scale128, 128)) return false;
    if (!InsertTableRows(scale129, 129)) return false;
    if (!InsertTableRows(scale130, 130)) return false;
    if (!InsertTableRows(scale131, 131)) return false;
    if (!InsertTableRows(scale132, 132)) return false;
    if (!InsertTableRows(scale133, 133)) return false;
    if (!InsertTableRows(scale134, 134)) return false;
    if (!InsertTableRows(scale135, 135)) return false;
    if (!InsertTableRows(scale136, 136)) return false;
    if (!InsertTableRows(scale137, 137)) return false;
    if (!InsertTableRows(scale138, 138)) return false;
    if (!InsertTableRows(scale139, 139)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup06() {
    scale120.Property<&Scale120::revision>().IsRequired();
    scale120.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale121.Property<&Scale121::revision>().IsRequired();
    scale121.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale122.Property<&Scale122::revision>().IsRequired();
    scale122.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale123.Property<&Scale123::revision>().IsRequired();
    scale123.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale124.Property<&Scale124::revision>().IsRequired();
    scale124.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale125.Property<&Scale125::revision>().IsRequired();
    scale125.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale126.Property<&Scale126::revision>().IsRequired();
    scale126.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale127.Property<&Scale127::revision>().IsRequired();
    scale127.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale128.Property<&Scale128::revision>().IsRequired();
    scale128.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale129.Property<&Scale129::revision>().IsRequired();
    scale129.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale130.Property<&Scale130::revision>().IsRequired();
    scale130.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale131.Property<&Scale131::revision>().IsRequired();
    scale131.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale132.Property<&Scale132::revision>().IsRequired();
    scale132.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale133.Property<&Scale133::revision>().IsRequired();
    scale133.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale134.Property<&Scale134::revision>().IsRequired();
    scale134.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale135.Property<&Scale135::revision>().IsRequired();
    scale135.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale136.Property<&Scale136::revision>().IsRequired();
    scale136.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale137.Property<&Scale137::revision>().IsRequired();
    scale137.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale138.Property<&Scale138::revision>().IsRequired();
    scale138.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale139.Property<&Scale139::revision>().IsRequired();
    scale139.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
