// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale240Map::ConfigureEntity(Q1Entity<Scale240>& entity) {
    entity.ToTableName("scale_240");
    entity.HasKey<&Scale240::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale240::name>().IsRequired();
    entity.Property<&Scale240::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale240::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale241Map::ConfigureEntity(Q1Entity<Scale241>& entity) {
    entity.ToTableName("scale_241");
    entity.HasKey<&Scale241::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale241::name>().IsRequired();
    entity.Property<&Scale241::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale241::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale242Map::ConfigureEntity(Q1Entity<Scale242>& entity) {
    entity.ToTableName("scale_242");
    entity.HasKey<&Scale242::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale242::name>().IsRequired();
    entity.Property<&Scale242::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale242::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale243Map::ConfigureEntity(Q1Entity<Scale243>& entity) {
    entity.ToTableName("scale_243");
    entity.HasKey<&Scale243::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale243::name>().IsRequired();
    entity.Property<&Scale243::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale243::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale244Map::ConfigureEntity(Q1Entity<Scale244>& entity) {
    entity.ToTableName("scale_244");
    entity.HasKey<&Scale244::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale244::name>().IsRequired();
    entity.Property<&Scale244::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale244::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale245Map::ConfigureEntity(Q1Entity<Scale245>& entity) {
    entity.ToTableName("scale_245");
    entity.HasKey<&Scale245::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale245::name>().IsRequired();
    entity.Property<&Scale245::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale245::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale246Map::ConfigureEntity(Q1Entity<Scale246>& entity) {
    entity.ToTableName("scale_246");
    entity.HasKey<&Scale246::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale246::name>().IsRequired();
    entity.Property<&Scale246::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale246::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale247Map::ConfigureEntity(Q1Entity<Scale247>& entity) {
    entity.ToTableName("scale_247");
    entity.HasKey<&Scale247::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale247::name>().IsRequired();
    entity.Property<&Scale247::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale247::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale248Map::ConfigureEntity(Q1Entity<Scale248>& entity) {
    entity.ToTableName("scale_248");
    entity.HasKey<&Scale248::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale248::name>().IsRequired();
    entity.Property<&Scale248::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale248::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale249Map::ConfigureEntity(Q1Entity<Scale249>& entity) {
    entity.ToTableName("scale_249");
    entity.HasKey<&Scale249::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale249::name>().IsRequired();
    entity.Property<&Scale249::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale249::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale250Map::ConfigureEntity(Q1Entity<Scale250>& entity) {
    entity.ToTableName("scale_250");
    entity.HasKey<&Scale250::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale250::name>().IsRequired();
    entity.Property<&Scale250::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale250::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale251Map::ConfigureEntity(Q1Entity<Scale251>& entity) {
    entity.ToTableName("scale_251");
    entity.HasKey<&Scale251::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale251::name>().IsRequired();
    entity.Property<&Scale251::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale251::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale252Map::ConfigureEntity(Q1Entity<Scale252>& entity) {
    entity.ToTableName("scale_252");
    entity.HasKey<&Scale252::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale252::name>().IsRequired();
    entity.Property<&Scale252::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale252::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale253Map::ConfigureEntity(Q1Entity<Scale253>& entity) {
    entity.ToTableName("scale_253");
    entity.HasKey<&Scale253::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale253::name>().IsRequired();
    entity.Property<&Scale253::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale253::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale254Map::ConfigureEntity(Q1Entity<Scale254>& entity) {
    entity.ToTableName("scale_254");
    entity.HasKey<&Scale254::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale254::name>().IsRequired();
    entity.Property<&Scale254::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale254::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale255Map::ConfigureEntity(Q1Entity<Scale255>& entity) {
    entity.ToTableName("scale_255");
    entity.HasKey<&Scale255::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale255::name>().IsRequired();
    entity.Property<&Scale255::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale255::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale256Map::ConfigureEntity(Q1Entity<Scale256>& entity) {
    entity.ToTableName("scale_256");
    entity.HasKey<&Scale256::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale256::name>().IsRequired();
    entity.Property<&Scale256::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale256::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale257Map::ConfigureEntity(Q1Entity<Scale257>& entity) {
    entity.ToTableName("scale_257");
    entity.HasKey<&Scale257::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale257::name>().IsRequired();
    entity.Property<&Scale257::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale257::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale258Map::ConfigureEntity(Q1Entity<Scale258>& entity) {
    entity.ToTableName("scale_258");
    entity.HasKey<&Scale258::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale258::name>().IsRequired();
    entity.Property<&Scale258::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale258::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale259Map::ConfigureEntity(Q1Entity<Scale259>& entity) {
    entity.ToTableName("scale_259");
    entity.HasKey<&Scale259::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale259::name>().IsRequired();
    entity.Property<&Scale259::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale259::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup12() {
    if (!InsertTableRows(scale240, 240)) return false;
    if (!InsertTableRows(scale241, 241)) return false;
    if (!InsertTableRows(scale242, 242)) return false;
    if (!InsertTableRows(scale243, 243)) return false;
    if (!InsertTableRows(scale244, 244)) return false;
    if (!InsertTableRows(scale245, 245)) return false;
    if (!InsertTableRows(scale246, 246)) return false;
    if (!InsertTableRows(scale247, 247)) return false;
    if (!InsertTableRows(scale248, 248)) return false;
    if (!InsertTableRows(scale249, 249)) return false;
    if (!InsertTableRows(scale250, 250)) return false;
    if (!InsertTableRows(scale251, 251)) return false;
    if (!InsertTableRows(scale252, 252)) return false;
    if (!InsertTableRows(scale253, 253)) return false;
    if (!InsertTableRows(scale254, 254)) return false;
    if (!InsertTableRows(scale255, 255)) return false;
    if (!InsertTableRows(scale256, 256)) return false;
    if (!InsertTableRows(scale257, 257)) return false;
    if (!InsertTableRows(scale258, 258)) return false;
    if (!InsertTableRows(scale259, 259)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup12() {
    scale240.Property<&Scale240::revision>().IsRequired();
    scale240.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale241.Property<&Scale241::revision>().IsRequired();
    scale241.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale242.Property<&Scale242::revision>().IsRequired();
    scale242.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale243.Property<&Scale243::revision>().IsRequired();
    scale243.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale244.Property<&Scale244::revision>().IsRequired();
    scale244.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale245.Property<&Scale245::revision>().IsRequired();
    scale245.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale246.Property<&Scale246::revision>().IsRequired();
    scale246.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale247.Property<&Scale247::revision>().IsRequired();
    scale247.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale248.Property<&Scale248::revision>().IsRequired();
    scale248.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale249.Property<&Scale249::revision>().IsRequired();
    scale249.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale250.Property<&Scale250::revision>().IsRequired();
    scale250.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale251.Property<&Scale251::revision>().IsRequired();
    scale251.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale252.Property<&Scale252::revision>().IsRequired();
    scale252.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale253.Property<&Scale253::revision>().IsRequired();
    scale253.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale254.Property<&Scale254::revision>().IsRequired();
    scale254.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale255.Property<&Scale255::revision>().IsRequired();
    scale255.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale256.Property<&Scale256::revision>().IsRequired();
    scale256.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale257.Property<&Scale257::revision>().IsRequired();
    scale257.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale258.Property<&Scale258::revision>().IsRequired();
    scale258.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale259.Property<&Scale259::revision>().IsRequired();
    scale259.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
