// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale260Map::ConfigureEntity(Q1Entity<Scale260>& entity) {
    entity.ToTableName("scale_260");
    entity.HasKey<&Scale260::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale260::name>().IsRequired();
    entity.Property<&Scale260::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale260::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale261Map::ConfigureEntity(Q1Entity<Scale261>& entity) {
    entity.ToTableName("scale_261");
    entity.HasKey<&Scale261::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale261::name>().IsRequired();
    entity.Property<&Scale261::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale261::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale262Map::ConfigureEntity(Q1Entity<Scale262>& entity) {
    entity.ToTableName("scale_262");
    entity.HasKey<&Scale262::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale262::name>().IsRequired();
    entity.Property<&Scale262::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale262::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale263Map::ConfigureEntity(Q1Entity<Scale263>& entity) {
    entity.ToTableName("scale_263");
    entity.HasKey<&Scale263::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale263::name>().IsRequired();
    entity.Property<&Scale263::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale263::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale264Map::ConfigureEntity(Q1Entity<Scale264>& entity) {
    entity.ToTableName("scale_264");
    entity.HasKey<&Scale264::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale264::name>().IsRequired();
    entity.Property<&Scale264::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale264::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale265Map::ConfigureEntity(Q1Entity<Scale265>& entity) {
    entity.ToTableName("scale_265");
    entity.HasKey<&Scale265::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale265::name>().IsRequired();
    entity.Property<&Scale265::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale265::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale266Map::ConfigureEntity(Q1Entity<Scale266>& entity) {
    entity.ToTableName("scale_266");
    entity.HasKey<&Scale266::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale266::name>().IsRequired();
    entity.Property<&Scale266::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale266::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale267Map::ConfigureEntity(Q1Entity<Scale267>& entity) {
    entity.ToTableName("scale_267");
    entity.HasKey<&Scale267::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale267::name>().IsRequired();
    entity.Property<&Scale267::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale267::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale268Map::ConfigureEntity(Q1Entity<Scale268>& entity) {
    entity.ToTableName("scale_268");
    entity.HasKey<&Scale268::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale268::name>().IsRequired();
    entity.Property<&Scale268::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale268::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale269Map::ConfigureEntity(Q1Entity<Scale269>& entity) {
    entity.ToTableName("scale_269");
    entity.HasKey<&Scale269::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale269::name>().IsRequired();
    entity.Property<&Scale269::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale269::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale270Map::ConfigureEntity(Q1Entity<Scale270>& entity) {
    entity.ToTableName("scale_270");
    entity.HasKey<&Scale270::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale270::name>().IsRequired();
    entity.Property<&Scale270::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale270::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale271Map::ConfigureEntity(Q1Entity<Scale271>& entity) {
    entity.ToTableName("scale_271");
    entity.HasKey<&Scale271::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale271::name>().IsRequired();
    entity.Property<&Scale271::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale271::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale272Map::ConfigureEntity(Q1Entity<Scale272>& entity) {
    entity.ToTableName("scale_272");
    entity.HasKey<&Scale272::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale272::name>().IsRequired();
    entity.Property<&Scale272::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale272::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale273Map::ConfigureEntity(Q1Entity<Scale273>& entity) {
    entity.ToTableName("scale_273");
    entity.HasKey<&Scale273::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale273::name>().IsRequired();
    entity.Property<&Scale273::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale273::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale274Map::ConfigureEntity(Q1Entity<Scale274>& entity) {
    entity.ToTableName("scale_274");
    entity.HasKey<&Scale274::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale274::name>().IsRequired();
    entity.Property<&Scale274::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale274::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale275Map::ConfigureEntity(Q1Entity<Scale275>& entity) {
    entity.ToTableName("scale_275");
    entity.HasKey<&Scale275::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale275::name>().IsRequired();
    entity.Property<&Scale275::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale275::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale276Map::ConfigureEntity(Q1Entity<Scale276>& entity) {
    entity.ToTableName("scale_276");
    entity.HasKey<&Scale276::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale276::name>().IsRequired();
    entity.Property<&Scale276::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale276::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale277Map::ConfigureEntity(Q1Entity<Scale277>& entity) {
    entity.ToTableName("scale_277");
    entity.HasKey<&Scale277::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale277::name>().IsRequired();
    entity.Property<&Scale277::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale277::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale278Map::ConfigureEntity(Q1Entity<Scale278>& entity) {
    entity.ToTableName("scale_278");
    entity.HasKey<&Scale278::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale278::name>().IsRequired();
    entity.Property<&Scale278::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale278::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale279Map::ConfigureEntity(Q1Entity<Scale279>& entity) {
    entity.ToTableName("scale_279");
    entity.HasKey<&Scale279::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale279::name>().IsRequired();
    entity.Property<&Scale279::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale279::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup13() {
    if (!InsertTableRows(scale260, 260)) return false;
    if (!InsertTableRows(scale261, 261)) return false;
    if (!InsertTableRows(scale262, 262)) return false;
    if (!InsertTableRows(scale263, 263)) return false;
    if (!InsertTableRows(scale264, 264)) return false;
    if (!InsertTableRows(scale265, 265)) return false;
    if (!InsertTableRows(scale266, 266)) return false;
    if (!InsertTableRows(scale267, 267)) return false;
    if (!InsertTableRows(scale268, 268)) return false;
    if (!InsertTableRows(scale269, 269)) return false;
    if (!InsertTableRows(scale270, 270)) return false;
    if (!InsertTableRows(scale271, 271)) return false;
    if (!InsertTableRows(scale272, 272)) return false;
    if (!InsertTableRows(scale273, 273)) return false;
    if (!InsertTableRows(scale274, 274)) return false;
    if (!InsertTableRows(scale275, 275)) return false;
    if (!InsertTableRows(scale276, 276)) return false;
    if (!InsertTableRows(scale277, 277)) return false;
    if (!InsertTableRows(scale278, 278)) return false;
    if (!InsertTableRows(scale279, 279)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup13() {
    scale260.Property<&Scale260::revision>().IsRequired();
    scale260.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale261.Property<&Scale261::revision>().IsRequired();
    scale261.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale262.Property<&Scale262::revision>().IsRequired();
    scale262.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale263.Property<&Scale263::revision>().IsRequired();
    scale263.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale264.Property<&Scale264::revision>().IsRequired();
    scale264.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale265.Property<&Scale265::revision>().IsRequired();
    scale265.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale266.Property<&Scale266::revision>().IsRequired();
    scale266.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale267.Property<&Scale267::revision>().IsRequired();
    scale267.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale268.Property<&Scale268::revision>().IsRequired();
    scale268.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale269.Property<&Scale269::revision>().IsRequired();
    scale269.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale270.Property<&Scale270::revision>().IsRequired();
    scale270.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale271.Property<&Scale271::revision>().IsRequired();
    scale271.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale272.Property<&Scale272::revision>().IsRequired();
    scale272.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale273.Property<&Scale273::revision>().IsRequired();
    scale273.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale274.Property<&Scale274::revision>().IsRequired();
    scale274.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale275.Property<&Scale275::revision>().IsRequired();
    scale275.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale276.Property<&Scale276::revision>().IsRequired();
    scale276.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale277.Property<&Scale277::revision>().IsRequired();
    scale277.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale278.Property<&Scale278::revision>().IsRequired();
    scale278.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale279.Property<&Scale279::revision>().IsRequired();
    scale279.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
