// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale020Map::ConfigureEntity(Q1Entity<Scale020>& entity) {
    entity.ToTableName("scale_020");
    entity.HasKey<&Scale020::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale020::name>().IsRequired();
    entity.Property<&Scale020::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale020::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale021Map::ConfigureEntity(Q1Entity<Scale021>& entity) {
    entity.ToTableName("scale_021");
    entity.HasKey<&Scale021::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale021::name>().IsRequired();
    entity.Property<&Scale021::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale021::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale022Map::ConfigureEntity(Q1Entity<Scale022>& entity) {
    entity.ToTableName("scale_022");
    entity.HasKey<&Scale022::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale022::name>().IsRequired();
    entity.Property<&Scale022::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale022::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale023Map::ConfigureEntity(Q1Entity<Scale023>& entity) {
    entity.ToTableName("scale_023");
    entity.HasKey<&Scale023::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale023::name>().IsRequired();
    entity.Property<&Scale023::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale023::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale024Map::ConfigureEntity(Q1Entity<Scale024>& entity) {
    entity.ToTableName("scale_024");
    entity.HasKey<&Scale024::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale024::name>().IsRequired();
    entity.Property<&Scale024::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale024::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale025Map::ConfigureEntity(Q1Entity<Scale025>& entity) {
    entity.ToTableName("scale_025");
    entity.HasKey<&Scale025::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale025::name>().IsRequired();
    entity.Property<&Scale025::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale025::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale026Map::ConfigureEntity(Q1Entity<Scale026>& entity) {
    entity.ToTableName("scale_026");
    entity.HasKey<&Scale026::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale026::name>().IsRequired();
    entity.Property<&Scale026::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale026::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale027Map::ConfigureEntity(Q1Entity<Scale027>& entity) {
    entity.ToTableName("scale_027");
    entity.HasKey<&Scale027::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale027::name>().IsRequired();
    entity.Property<&Scale027::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale027::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale028Map::ConfigureEntity(Q1Entity<Scale028>& entity) {
    entity.ToTableName("scale_028");
    entity.HasKey<&Scale028::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale028::name>().IsRequired();
    entity.Property<&Scale028::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale028::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale029Map::ConfigureEntity(Q1Entity<Scale029>& entity) {
    entity.ToTableName("scale_029");
    entity.HasKey<&Scale029::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale029::name>().IsRequired();
    entity.Property<&Scale029::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale029::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale030Map::ConfigureEntity(Q1Entity<Scale030>& entity) {
    entity.ToTableName("scale_030");
    entity.HasKey<&Scale030::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale030::name>().IsRequired();
    entity.Property<&Scale030::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale030::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale031Map::ConfigureEntity(Q1Entity<Scale031>& entity) {
    entity.ToTableName("scale_031");
    entity.HasKey<&Scale031::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale031::name>().IsRequired();
    entity.Property<&Scale031::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale031::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale032Map::ConfigureEntity(Q1Entity<Scale032>& entity) {
    entity.ToTableName("scale_032");
    entity.HasKey<&Scale032::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale032::name>().IsRequired();
    entity.Property<&Scale032::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale032::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale033Map::ConfigureEntity(Q1Entity<Scale033>& entity) {
    entity.ToTableName("scale_033");
    entity.HasKey<&Scale033::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale033::name>().IsRequired();
    entity.Property<&Scale033::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale033::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale034Map::ConfigureEntity(Q1Entity<Scale034>& entity) {
    entity.ToTableName("scale_034");
    entity.HasKey<&Scale034::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale034::name>().IsRequired();
    entity.Property<&Scale034::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale034::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale035Map::ConfigureEntity(Q1Entity<Scale035>& entity) {
    entity.ToTableName("scale_035");
    entity.HasKey<&Scale035::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale035::name>().IsRequired();
    entity.Property<&Scale035::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale035::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale036Map::ConfigureEntity(Q1Entity<Scale036>& entity) {
    entity.ToTableName("scale_036");
    entity.HasKey<&Scale036::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale036::name>().IsRequired();
    entity.Property<&Scale036::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale036::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale037Map::ConfigureEntity(Q1Entity<Scale037>& entity) {
    entity.ToTableName("scale_037");
    entity.HasKey<&Scale037::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale037::name>().IsRequired();
    entity.Property<&Scale037::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale037::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale038Map::ConfigureEntity(Q1Entity<Scale038>& entity) {
    entity.ToTableName("scale_038");
    entity.HasKey<&Scale038::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale038::name>().IsRequired();
    entity.Property<&Scale038::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale038::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale039Map::ConfigureEntity(Q1Entity<Scale039>& entity) {
    entity.ToTableName("scale_039");
    entity.HasKey<&Scale039::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale039::name>().IsRequired();
    entity.Property<&Scale039::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale039::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup01() {
    if (!InsertTableRows(scale020, 20)) return false;
    if (!InsertTableRows(scale021, 21)) return false;
    if (!InsertTableRows(scale022, 22)) return false;
    if (!InsertTableRows(scale023, 23)) return false;
    if (!InsertTableRows(scale024, 24)) return false;
    if (!InsertTableRows(scale025, 25)) return false;
    if (!InsertTableRows(scale026, 26)) return false;
    if (!InsertTableRows(scale027, 27)) return false;
    if (!InsertTableRows(scale028, 28)) return false;
    if (!InsertTableRows(scale029, 29)) return false;
    if (!InsertTableRows(scale030, 30)) return false;
    if (!InsertTableRows(scale031, 31)) return false;
    if (!InsertTableRows(scale032, 32)) return false;
    if (!InsertTableRows(scale033, 33)) return false;
    if (!InsertTableRows(scale034, 34)) return false;
    if (!InsertTableRows(scale035, 35)) return false;
    if (!InsertTableRows(scale036, 36)) return false;
    if (!InsertTableRows(scale037, 37)) return false;
    if (!InsertTableRows(scale038, 38)) return false;
    if (!InsertTableRows(scale039, 39)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup01() {
    scale020.Property<&Scale020::revision>().IsRequired();
    scale020.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale021.Property<&Scale021::revision>().IsRequired();
    scale021.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale022.Property<&Scale022::revision>().IsRequired();
    scale022.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale023.Property<&Scale023::revision>().IsRequired();
    scale023.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale024.Property<&Scale024::revision>().IsRequired();
    scale024.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale025.Property<&Scale025::revision>().IsRequired();
    scale025.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale026.Property<&Scale026::revision>().IsRequired();
    scale026.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale027.Property<&Scale027::revision>().IsRequired();
    scale027.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale028.Property<&Scale028::revision>().IsRequired();
    scale028.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale029.Property<&Scale029::revision>().IsRequired();
    scale029.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale030.Property<&Scale030::revision>().IsRequired();
    scale030.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale031.Property<&Scale031::revision>().IsRequired();
    scale031.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale032.Property<&Scale032::revision>().IsRequired();
    scale032.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale033.Property<&Scale033::revision>().IsRequired();
    scale033.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale034.Property<&Scale034::revision>().IsRequired();
    scale034.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale035.Property<&Scale035::revision>().IsRequired();
    scale035.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale036.Property<&Scale036::revision>().IsRequired();
    scale036.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale037.Property<&Scale037::revision>().IsRequired();
    scale037.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale038.Property<&Scale038::revision>().IsRequired();
    scale038.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale039.Property<&Scale039::revision>().IsRequired();
    scale039.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
