// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale100Map::ConfigureEntity(Q1Entity<Scale100>& entity) {
    entity.ToTableName("scale_100");
    entity.HasKey<&Scale100::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale100::name>().IsRequired();
    entity.Property<&Scale100::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale100::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale101Map::ConfigureEntity(Q1Entity<Scale101>& entity) {
    entity.ToTableName("scale_101");
    entity.HasKey<&Scale101::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale101::name>().IsRequired();
    entity.Property<&Scale101::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale101::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale102Map::ConfigureEntity(Q1Entity<Scale102>& entity) {
    entity.ToTableName("scale_102");
    entity.HasKey<&Scale102::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale102::name>().IsRequired();
    entity.Property<&Scale102::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale102::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale103Map::ConfigureEntity(Q1Entity<Scale103>& entity) {
    entity.ToTableName("scale_103");
    entity.HasKey<&Scale103::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale103::name>().IsRequired();
    entity.Property<&Scale103::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale103::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale104Map::ConfigureEntity(Q1Entity<Scale104>& entity) {
    entity.ToTableName("scale_104");
    entity.HasKey<&Scale104::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale104::name>().IsRequired();
    entity.Property<&Scale104::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale104::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale105Map::ConfigureEntity(Q1Entity<Scale105>& entity) {
    entity.ToTableName("scale_105");
    entity.HasKey<&Scale105::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale105::name>().IsRequired();
    entity.Property<&Scale105::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale105::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale106Map::ConfigureEntity(Q1Entity<Scale106>& entity) {
    entity.ToTableName("scale_106");
    entity.HasKey<&Scale106::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale106::name>().IsRequired();
    entity.Property<&Scale106::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale106::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale107Map::ConfigureEntity(Q1Entity<Scale107>& entity) {
    entity.ToTableName("scale_107");
    entity.HasKey<&Scale107::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale107::name>().IsRequired();
    entity.Property<&Scale107::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale107::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale108Map::ConfigureEntity(Q1Entity<Scale108>& entity) {
    entity.ToTableName("scale_108");
    entity.HasKey<&Scale108::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale108::name>().IsRequired();
    entity.Property<&Scale108::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale108::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale109Map::ConfigureEntity(Q1Entity<Scale109>& entity) {
    entity.ToTableName("scale_109");
    entity.HasKey<&Scale109::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale109::name>().IsRequired();
    entity.Property<&Scale109::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale109::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale110Map::ConfigureEntity(Q1Entity<Scale110>& entity) {
    entity.ToTableName("scale_110");
    entity.HasKey<&Scale110::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale110::name>().IsRequired();
    entity.Property<&Scale110::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale110::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale111Map::ConfigureEntity(Q1Entity<Scale111>& entity) {
    entity.ToTableName("scale_111");
    entity.HasKey<&Scale111::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale111::name>().IsRequired();
    entity.Property<&Scale111::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale111::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale112Map::ConfigureEntity(Q1Entity<Scale112>& entity) {
    entity.ToTableName("scale_112");
    entity.HasKey<&Scale112::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale112::name>().IsRequired();
    entity.Property<&Scale112::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale112::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale113Map::ConfigureEntity(Q1Entity<Scale113>& entity) {
    entity.ToTableName("scale_113");
    entity.HasKey<&Scale113::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale113::name>().IsRequired();
    entity.Property<&Scale113::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale113::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale114Map::ConfigureEntity(Q1Entity<Scale114>& entity) {
    entity.ToTableName("scale_114");
    entity.HasKey<&Scale114::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale114::name>().IsRequired();
    entity.Property<&Scale114::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale114::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale115Map::ConfigureEntity(Q1Entity<Scale115>& entity) {
    entity.ToTableName("scale_115");
    entity.HasKey<&Scale115::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale115::name>().IsRequired();
    entity.Property<&Scale115::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale115::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale116Map::ConfigureEntity(Q1Entity<Scale116>& entity) {
    entity.ToTableName("scale_116");
    entity.HasKey<&Scale116::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale116::name>().IsRequired();
    entity.Property<&Scale116::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale116::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale117Map::ConfigureEntity(Q1Entity<Scale117>& entity) {
    entity.ToTableName("scale_117");
    entity.HasKey<&Scale117::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale117::name>().IsRequired();
    entity.Property<&Scale117::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale117::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale118Map::ConfigureEntity(Q1Entity<Scale118>& entity) {
    entity.ToTableName("scale_118");
    entity.HasKey<&Scale118::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale118::name>().IsRequired();
    entity.Property<&Scale118::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale118::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale119Map::ConfigureEntity(Q1Entity<Scale119>& entity) {
    entity.ToTableName("scale_119");
    entity.HasKey<&Scale119::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale119::name>().IsRequired();
    entity.Property<&Scale119::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale119::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup05() {
    if (!InsertTableRows(scale100, 100)) return false;
    if (!InsertTableRows(scale101, 101)) return false;
    if (!InsertTableRows(scale102, 102)) return false;
    if (!InsertTableRows(scale103, 103)) return false;
    if (!InsertTableRows(scale104, 104)) return false;
    if (!InsertTableRows(scale105, 105)) return false;
    if (!InsertTableRows(scale106, 106)) return false;
    if (!InsertTableRows(scale107, 107)) return false;
    if (!InsertTableRows(scale108, 108)) return false;
    if (!InsertTableRows(scale109, 109)) return false;
    if (!InsertTableRows(scale110, 110)) return false;
    if (!InsertTableRows(scale111, 111)) return false;
    if (!InsertTableRows(scale112, 112)) return false;
    if (!InsertTableRows(scale113, 113)) return false;
    if (!InsertTableRows(scale114, 114)) return false;
    if (!InsertTableRows(scale115, 115)) return false;
    if (!InsertTableRows(scale116, 116)) return false;
    if (!InsertTableRows(scale117, 117)) return false;
    if (!InsertTableRows(scale118, 118)) return false;
    if (!InsertTableRows(scale119, 119)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup05() {
    scale100.Property<&Scale100::revision>().IsRequired();
    scale100.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale101.Property<&Scale101::revision>().IsRequired();
    scale101.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale102.Property<&Scale102::revision>().IsRequired();
    scale102.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale103.Property<&Scale103::revision>().IsRequired();
    scale103.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale104.Property<&Scale104::revision>().IsRequired();
    scale104.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale105.Property<&Scale105::revision>().IsRequired();
    scale105.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale106.Property<&Scale106::revision>().IsRequired();
    scale106.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale107.Property<&Scale107::revision>().IsRequired();
    scale107.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale108.Property<&Scale108::revision>().IsRequired();
    scale108.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale109.Property<&Scale109::revision>().IsRequired();
    scale109.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale110.Property<&Scale110::revision>().IsRequired();
    scale110.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale111.Property<&Scale111::revision>().IsRequired();
    scale111.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale112.Property<&Scale112::revision>().IsRequired();
    scale112.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale113.Property<&Scale113::revision>().IsRequired();
    scale113.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale114.Property<&Scale114::revision>().IsRequired();
    scale114.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale115.Property<&Scale115::revision>().IsRequired();
    scale115.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale116.Property<&Scale116::revision>().IsRequired();
    scale116.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale117.Property<&Scale117::revision>().IsRequired();
    scale117.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale118.Property<&Scale118::revision>().IsRequired();
    scale118.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale119.Property<&Scale119::revision>().IsRequired();
    scale119.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
