// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale040Map::ConfigureEntity(Q1Entity<Scale040>& entity) {
    entity.ToTableName("scale_040");
    entity.HasKey<&Scale040::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale040::name>().IsRequired();
    entity.Property<&Scale040::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale040::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale041Map::ConfigureEntity(Q1Entity<Scale041>& entity) {
    entity.ToTableName("scale_041");
    entity.HasKey<&Scale041::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale041::name>().IsRequired();
    entity.Property<&Scale041::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale041::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale042Map::ConfigureEntity(Q1Entity<Scale042>& entity) {
    entity.ToTableName("scale_042");
    entity.HasKey<&Scale042::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale042::name>().IsRequired();
    entity.Property<&Scale042::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale042::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale043Map::ConfigureEntity(Q1Entity<Scale043>& entity) {
    entity.ToTableName("scale_043");
    entity.HasKey<&Scale043::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale043::name>().IsRequired();
    entity.Property<&Scale043::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale043::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale044Map::ConfigureEntity(Q1Entity<Scale044>& entity) {
    entity.ToTableName("scale_044");
    entity.HasKey<&Scale044::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale044::name>().IsRequired();
    entity.Property<&Scale044::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale044::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale045Map::ConfigureEntity(Q1Entity<Scale045>& entity) {
    entity.ToTableName("scale_045");
    entity.HasKey<&Scale045::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale045::name>().IsRequired();
    entity.Property<&Scale045::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale045::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale046Map::ConfigureEntity(Q1Entity<Scale046>& entity) {
    entity.ToTableName("scale_046");
    entity.HasKey<&Scale046::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale046::name>().IsRequired();
    entity.Property<&Scale046::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale046::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale047Map::ConfigureEntity(Q1Entity<Scale047>& entity) {
    entity.ToTableName("scale_047");
    entity.HasKey<&Scale047::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale047::name>().IsRequired();
    entity.Property<&Scale047::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale047::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale048Map::ConfigureEntity(Q1Entity<Scale048>& entity) {
    entity.ToTableName("scale_048");
    entity.HasKey<&Scale048::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale048::name>().IsRequired();
    entity.Property<&Scale048::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale048::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale049Map::ConfigureEntity(Q1Entity<Scale049>& entity) {
    entity.ToTableName("scale_049");
    entity.HasKey<&Scale049::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale049::name>().IsRequired();
    entity.Property<&Scale049::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale049::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale050Map::ConfigureEntity(Q1Entity<Scale050>& entity) {
    entity.ToTableName("scale_050");
    entity.HasKey<&Scale050::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale050::name>().IsRequired();
    entity.Property<&Scale050::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale050::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale051Map::ConfigureEntity(Q1Entity<Scale051>& entity) {
    entity.ToTableName("scale_051");
    entity.HasKey<&Scale051::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale051::name>().IsRequired();
    entity.Property<&Scale051::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale051::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale052Map::ConfigureEntity(Q1Entity<Scale052>& entity) {
    entity.ToTableName("scale_052");
    entity.HasKey<&Scale052::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale052::name>().IsRequired();
    entity.Property<&Scale052::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale052::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale053Map::ConfigureEntity(Q1Entity<Scale053>& entity) {
    entity.ToTableName("scale_053");
    entity.HasKey<&Scale053::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale053::name>().IsRequired();
    entity.Property<&Scale053::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale053::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale054Map::ConfigureEntity(Q1Entity<Scale054>& entity) {
    entity.ToTableName("scale_054");
    entity.HasKey<&Scale054::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale054::name>().IsRequired();
    entity.Property<&Scale054::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale054::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale055Map::ConfigureEntity(Q1Entity<Scale055>& entity) {
    entity.ToTableName("scale_055");
    entity.HasKey<&Scale055::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale055::name>().IsRequired();
    entity.Property<&Scale055::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale055::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale056Map::ConfigureEntity(Q1Entity<Scale056>& entity) {
    entity.ToTableName("scale_056");
    entity.HasKey<&Scale056::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale056::name>().IsRequired();
    entity.Property<&Scale056::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale056::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale057Map::ConfigureEntity(Q1Entity<Scale057>& entity) {
    entity.ToTableName("scale_057");
    entity.HasKey<&Scale057::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale057::name>().IsRequired();
    entity.Property<&Scale057::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale057::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale058Map::ConfigureEntity(Q1Entity<Scale058>& entity) {
    entity.ToTableName("scale_058");
    entity.HasKey<&Scale058::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale058::name>().IsRequired();
    entity.Property<&Scale058::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale058::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale059Map::ConfigureEntity(Q1Entity<Scale059>& entity) {
    entity.ToTableName("scale_059");
    entity.HasKey<&Scale059::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale059::name>().IsRequired();
    entity.Property<&Scale059::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale059::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup02() {
    if (!InsertTableRows(scale040, 40)) return false;
    if (!InsertTableRows(scale041, 41)) return false;
    if (!InsertTableRows(scale042, 42)) return false;
    if (!InsertTableRows(scale043, 43)) return false;
    if (!InsertTableRows(scale044, 44)) return false;
    if (!InsertTableRows(scale045, 45)) return false;
    if (!InsertTableRows(scale046, 46)) return false;
    if (!InsertTableRows(scale047, 47)) return false;
    if (!InsertTableRows(scale048, 48)) return false;
    if (!InsertTableRows(scale049, 49)) return false;
    if (!InsertTableRows(scale050, 50)) return false;
    if (!InsertTableRows(scale051, 51)) return false;
    if (!InsertTableRows(scale052, 52)) return false;
    if (!InsertTableRows(scale053, 53)) return false;
    if (!InsertTableRows(scale054, 54)) return false;
    if (!InsertTableRows(scale055, 55)) return false;
    if (!InsertTableRows(scale056, 56)) return false;
    if (!InsertTableRows(scale057, 57)) return false;
    if (!InsertTableRows(scale058, 58)) return false;
    if (!InsertTableRows(scale059, 59)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup02() {
    scale040.Property<&Scale040::revision>().IsRequired();
    scale040.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale041.Property<&Scale041::revision>().IsRequired();
    scale041.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale042.Property<&Scale042::revision>().IsRequired();
    scale042.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale043.Property<&Scale043::revision>().IsRequired();
    scale043.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale044.Property<&Scale044::revision>().IsRequired();
    scale044.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale045.Property<&Scale045::revision>().IsRequired();
    scale045.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale046.Property<&Scale046::revision>().IsRequired();
    scale046.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale047.Property<&Scale047::revision>().IsRequired();
    scale047.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale048.Property<&Scale048::revision>().IsRequired();
    scale048.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale049.Property<&Scale049::revision>().IsRequired();
    scale049.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale050.Property<&Scale050::revision>().IsRequired();
    scale050.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale051.Property<&Scale051::revision>().IsRequired();
    scale051.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale052.Property<&Scale052::revision>().IsRequired();
    scale052.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale053.Property<&Scale053::revision>().IsRequired();
    scale053.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale054.Property<&Scale054::revision>().IsRequired();
    scale054.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale055.Property<&Scale055::revision>().IsRequired();
    scale055.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale056.Property<&Scale056::revision>().IsRequired();
    scale056.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale057.Property<&Scale057::revision>().IsRequired();
    scale057.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale058.Property<&Scale058::revision>().IsRequired();
    scale058.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale059.Property<&Scale059::revision>().IsRequired();
    scale059.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
