// Generated by generate_models.py; edit the generator to regenerate this fixture.
#include "ApplicationDbContext.h"
#include "Maps.h"
#include "TestData.h"

namespace SchemaScale {
void Scale200Map::ConfigureEntity(Q1Entity<Scale200>& entity) {
    entity.ToTableName("scale_200");
    entity.HasKey<&Scale200::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale200::name>().IsRequired();
    entity.Property<&Scale200::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale200::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale201Map::ConfigureEntity(Q1Entity<Scale201>& entity) {
    entity.ToTableName("scale_201");
    entity.HasKey<&Scale201::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale201::name>().IsRequired();
    entity.Property<&Scale201::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale201::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale202Map::ConfigureEntity(Q1Entity<Scale202>& entity) {
    entity.ToTableName("scale_202");
    entity.HasKey<&Scale202::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale202::name>().IsRequired();
    entity.Property<&Scale202::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale202::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale203Map::ConfigureEntity(Q1Entity<Scale203>& entity) {
    entity.ToTableName("scale_203");
    entity.HasKey<&Scale203::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale203::name>().IsRequired();
    entity.Property<&Scale203::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale203::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale204Map::ConfigureEntity(Q1Entity<Scale204>& entity) {
    entity.ToTableName("scale_204");
    entity.HasKey<&Scale204::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale204::name>().IsRequired();
    entity.Property<&Scale204::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale204::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale205Map::ConfigureEntity(Q1Entity<Scale205>& entity) {
    entity.ToTableName("scale_205");
    entity.HasKey<&Scale205::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale205::name>().IsRequired();
    entity.Property<&Scale205::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale205::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale206Map::ConfigureEntity(Q1Entity<Scale206>& entity) {
    entity.ToTableName("scale_206");
    entity.HasKey<&Scale206::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale206::name>().IsRequired();
    entity.Property<&Scale206::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale206::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale207Map::ConfigureEntity(Q1Entity<Scale207>& entity) {
    entity.ToTableName("scale_207");
    entity.HasKey<&Scale207::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale207::name>().IsRequired();
    entity.Property<&Scale207::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale207::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale208Map::ConfigureEntity(Q1Entity<Scale208>& entity) {
    entity.ToTableName("scale_208");
    entity.HasKey<&Scale208::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale208::name>().IsRequired();
    entity.Property<&Scale208::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale208::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale209Map::ConfigureEntity(Q1Entity<Scale209>& entity) {
    entity.ToTableName("scale_209");
    entity.HasKey<&Scale209::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale209::name>().IsRequired();
    entity.Property<&Scale209::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale209::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale210Map::ConfigureEntity(Q1Entity<Scale210>& entity) {
    entity.ToTableName("scale_210");
    entity.HasKey<&Scale210::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale210::name>().IsRequired();
    entity.Property<&Scale210::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale210::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale211Map::ConfigureEntity(Q1Entity<Scale211>& entity) {
    entity.ToTableName("scale_211");
    entity.HasKey<&Scale211::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale211::name>().IsRequired();
    entity.Property<&Scale211::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale211::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale212Map::ConfigureEntity(Q1Entity<Scale212>& entity) {
    entity.ToTableName("scale_212");
    entity.HasKey<&Scale212::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale212::name>().IsRequired();
    entity.Property<&Scale212::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale212::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale213Map::ConfigureEntity(Q1Entity<Scale213>& entity) {
    entity.ToTableName("scale_213");
    entity.HasKey<&Scale213::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale213::name>().IsRequired();
    entity.Property<&Scale213::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale213::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale214Map::ConfigureEntity(Q1Entity<Scale214>& entity) {
    entity.ToTableName("scale_214");
    entity.HasKey<&Scale214::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale214::name>().IsRequired();
    entity.Property<&Scale214::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale214::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale215Map::ConfigureEntity(Q1Entity<Scale215>& entity) {
    entity.ToTableName("scale_215");
    entity.HasKey<&Scale215::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale215::name>().IsRequired();
    entity.Property<&Scale215::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale215::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale216Map::ConfigureEntity(Q1Entity<Scale216>& entity) {
    entity.ToTableName("scale_216");
    entity.HasKey<&Scale216::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale216::name>().IsRequired();
    entity.Property<&Scale216::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale216::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale217Map::ConfigureEntity(Q1Entity<Scale217>& entity) {
    entity.ToTableName("scale_217");
    entity.HasKey<&Scale217::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale217::name>().IsRequired();
    entity.Property<&Scale217::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale217::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale218Map::ConfigureEntity(Q1Entity<Scale218>& entity) {
    entity.ToTableName("scale_218");
    entity.HasKey<&Scale218::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale218::name>().IsRequired();
    entity.Property<&Scale218::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale218::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

void Scale219Map::ConfigureEntity(Q1Entity<Scale219>& entity) {
    entity.ToTableName("scale_219");
    entity.HasKey<&Scale219::id>().ValueGeneratedOnAdd();
    entity.Property<&Scale219::name>().IsRequired();
    entity.Property<&Scale219::parent_id>();
    entity.HasOne<Scale000>().WithMany()
        .HasForeignKey<&Scale219::parent_id>()
        .HasPrincipalKey<&Scale000::id>();
    entity.GetTablePtr()->AddIndex({"name"});
}

bool ApplicationDbContext::InsertGroup10() {
    if (!InsertTableRows(scale200, 200)) return false;
    if (!InsertTableRows(scale201, 201)) return false;
    if (!InsertTableRows(scale202, 202)) return false;
    if (!InsertTableRows(scale203, 203)) return false;
    if (!InsertTableRows(scale204, 204)) return false;
    if (!InsertTableRows(scale205, 205)) return false;
    if (!InsertTableRows(scale206, 206)) return false;
    if (!InsertTableRows(scale207, 207)) return false;
    if (!InsertTableRows(scale208, 208)) return false;
    if (!InsertTableRows(scale209, 209)) return false;
    if (!InsertTableRows(scale210, 210)) return false;
    if (!InsertTableRows(scale211, 211)) return false;
    if (!InsertTableRows(scale212, 212)) return false;
    if (!InsertTableRows(scale213, 213)) return false;
    if (!InsertTableRows(scale214, 214)) return false;
    if (!InsertTableRows(scale215, 215)) return false;
    if (!InsertTableRows(scale216, 216)) return false;
    if (!InsertTableRows(scale217, 217)) return false;
    if (!InsertTableRows(scale218, 218)) return false;
    if (!InsertTableRows(scale219, 219)) return false;
    return true;
}

void ApplicationDbContext::AddRevisionGroup10() {
    scale200.Property<&Scale200::revision>().IsRequired();
    scale200.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale201.Property<&Scale201::revision>().IsRequired();
    scale201.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale202.Property<&Scale202::revision>().IsRequired();
    scale202.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale203.Property<&Scale203::revision>().IsRequired();
    scale203.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale204.Property<&Scale204::revision>().IsRequired();
    scale204.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale205.Property<&Scale205::revision>().IsRequired();
    scale205.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale206.Property<&Scale206::revision>().IsRequired();
    scale206.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale207.Property<&Scale207::revision>().IsRequired();
    scale207.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale208.Property<&Scale208::revision>().IsRequired();
    scale208.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale209.Property<&Scale209::revision>().IsRequired();
    scale209.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale210.Property<&Scale210::revision>().IsRequired();
    scale210.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale211.Property<&Scale211::revision>().IsRequired();
    scale211.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale212.Property<&Scale212::revision>().IsRequired();
    scale212.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale213.Property<&Scale213::revision>().IsRequired();
    scale213.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale214.Property<&Scale214::revision>().IsRequired();
    scale214.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale215.Property<&Scale215::revision>().IsRequired();
    scale215.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale216.Property<&Scale216::revision>().IsRequired();
    scale216.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale217.Property<&Scale217::revision>().IsRequired();
    scale217.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale218.Property<&Scale218::revision>().IsRequired();
    scale218.GetTablePtr()->FindColumn("revision")->default_value = "7";
    scale219.Property<&Scale219::revision>().IsRequired();
    scale219.GetTablePtr()->FindColumn("revision")->default_value = "7";
}
} // namespace SchemaScale
