// Generated by generate_models.py; edit the generator to regenerate this fixture.
#pragma once
#include <QString>

namespace SchemaScale {
struct Scale000 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale001 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale002 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale003 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale004 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale005 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale006 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale007 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale008 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale009 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale010 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale011 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale012 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale013 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale014 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale015 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale016 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale017 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale018 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale019 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale020 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale021 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale022 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale023 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale024 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale025 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale026 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale027 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale028 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale029 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale030 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale031 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale032 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale033 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale034 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale035 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale036 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale037 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale038 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale039 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale040 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale041 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale042 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale043 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale044 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale045 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale046 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale047 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale048 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale049 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale050 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale051 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale052 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale053 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale054 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale055 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale056 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale057 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale058 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale059 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale060 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale061 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale062 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale063 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale064 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale065 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale066 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale067 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale068 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale069 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale070 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale071 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale072 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale073 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale074 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale075 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale076 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale077 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale078 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale079 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale080 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale081 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale082 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale083 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale084 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale085 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale086 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale087 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale088 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale089 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale090 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale091 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale092 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale093 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale094 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale095 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale096 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale097 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale098 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale099 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale100 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale101 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale102 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale103 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale104 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale105 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale106 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale107 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale108 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale109 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale110 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale111 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale112 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale113 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale114 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale115 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale116 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale117 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale118 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale119 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale120 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale121 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale122 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale123 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale124 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale125 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale126 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale127 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale128 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale129 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale130 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale131 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale132 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale133 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale134 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale135 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale136 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale137 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale138 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale139 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale140 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale141 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale142 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale143 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale144 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale145 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale146 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale147 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale148 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale149 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale150 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale151 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale152 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale153 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale154 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale155 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale156 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale157 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale158 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale159 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale160 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale161 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale162 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale163 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale164 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale165 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale166 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale167 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale168 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale169 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale170 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale171 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale172 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale173 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale174 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale175 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale176 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale177 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale178 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale179 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale180 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale181 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale182 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale183 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale184 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale185 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale186 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale187 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale188 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale189 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale190 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale191 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale192 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale193 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale194 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale195 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale196 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale197 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale198 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale199 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale200 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale201 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale202 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale203 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale204 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale205 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale206 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale207 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale208 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale209 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale210 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale211 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale212 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale213 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale214 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale215 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale216 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale217 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale218 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale219 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale220 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale221 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale222 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale223 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale224 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale225 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale226 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale227 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale228 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale229 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale230 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale231 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale232 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale233 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale234 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale235 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale236 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale237 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale238 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale239 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale240 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale241 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale242 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale243 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale244 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale245 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale246 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale247 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale248 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale249 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale250 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale251 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale252 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale253 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale254 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale255 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale256 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale257 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale258 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale259 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale260 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale261 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale262 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale263 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale264 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale265 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale266 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale267 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale268 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale269 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale270 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale271 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale272 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale273 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale274 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale275 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale276 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale277 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale278 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale279 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale280 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale281 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale282 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale283 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale284 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale285 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale286 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale287 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale288 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale289 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale290 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale291 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale292 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale293 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale294 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale295 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale296 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale297 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale298 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

struct Scale299 {
    int id = 0;
    QString name;
    int parent_id = 0;
    int revision = 0;
};

} // namespace SchemaScale
