#pragma once
#include <Q1ORM.h>

namespace SchemaScale {
constexpr int tableCount = 300;
constexpr int rowsPerTable = 100;

inline QString tableName(int index) {
    return QString("scale_%1").arg(index, 3, 10, QLatin1Char('0'));
}
inline QString rowName(int table, int row) {
    return QString("table-%1-row-%2").arg(table).arg(row);
}

template <typename T>
bool InsertTableRows(Q1Entity<T>& entity, int table) {
    for (int row = 1; row <= rowsPerTable; ++row) {
        T value;
        value.name = rowName(table, row);
        value.parent_id = row;
        // IDs must be generated by the database and returned through the ORM.
        if (!entity.Insert(value) || value.id != row) {
            qCritical() << "Insert or generated ID failed:" << tableName(table) << "row" << row;
            return false;
        }
    }
    return true;
}
} // namespace SchemaScale
